### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded while getting the str of an object

### ISSUE THREAD

**Issue by labrys** [guessit-io/guessit#247]
When attempting to `.get` a value from a BS4 `.string`, I intermittently get a recursion depth error.

Test:

``` python
import requests
from bs4 import BeautifulSoup
from guessit import guessit

feed = requests.get('http://rarbg.com/rss.php')
if feed:
    soup = BeautifulSoup(feed.content, 'html.parser')
    for each in soup.rss.channel.find_all('item'):
        print(guessit(each.title.string).get('release_group'))
```

This is a low priority however since `print(guessit(str(each.title.string)).get('release_group'))` works just fine.  I would also be fine if you choose not to fix this as a BS4 `.string` is not an actual string.

**Comment by Toilal** [comment]
Which python version do you run for this test ?

**Comment by labrys** [comment]
2.7.10 iirc but it may have been 3.5.1

**Comment by ratoaq2** [comment]
I'm unable to reproduce this one with current guessit version.
@labrys Are you still able to eventually reproduce this one?

**Comment by labrys** [comment]
@ratoaq2 This is a python-3 issue.  

Tested today with code listed in original post using latest `guessit`, `requests` and `beautifulsoup4`

**Works with:**
* `Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32`
* `Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32`
* `Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32`

**Could not test with:**
* `Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AMD64)] on win32` Guessit fails to install with pip

**Fails with:** 
* `Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)] on win32`
* `Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32`
* `Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)] on win32`

**Comment by ratoaq2** [comment]
Here's part of the traceback using python 3.6:

```
Traceback (most recent call last):
  File "abc.py", line 9, in <module>
    print(guessit(each.title.string).get('release_group'))
  File "/home/user/workspace/git/guessit/guessit/api.py", line 54, in guessit
    return default_api.guessit(string, options)
  File "/home/user/workspace/git/guessit/guessit/api.py", line 132, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.0.0.dev0
string=BathroomCreepers.17.11.08.Daniela.XXX.1080p.MP4-KTR
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/workspace/git/guessit/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/site-packages/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/site-packages/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/site-packages/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/site-packages/rebulk/rules.py", line 339, in execute_rule
    when_response = rule.when(matches, context)
  File "/home/user/workspace/git/guessit/guessit/rules/properties/title.py", line 257, in when
    titles = self.check_titles_in_filepart(filepart, matches, context)
  File "/home/user/workspace/git/guessit/guessit/rules/properties/title.py", line 161, in check_titles_in_filepart
    holes = self.holes_process(holes, matches)
  File "/home/user/workspace/git/guessit/guessit/rules/properties/title.py", line 90, in holes_process
    cropped_holes.extend(hole.crop(group_markers))
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/site-packages/rebulk/match.py", line 761, in crop
    initial = copy.deepcopy(self)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/user/workspace/git/guessit/venv/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
```

**Comment by labrys** [comment]
Does this allow it to work with beautifulsoup now?  Also any idea why it worked for 3.5.3?
