### ISSUE TITLE
flexget ore guessit

### ISSUE THREAD

**Issue by crack00r** [guessit-io/guessit#263]
Hi, i use flexget, and when i have enabled guessit in my config, flexget allways crash.

the log is:
2016-01-30 09:08 CRITICAL task          premieren_en    BUG: Unhandled error in plugin series_premiere: 'latin-1' codec can't encode character u'\u2013' in position 23: ordinal not in range(256)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series_premiere.py", line 62, in on_task_metainfo
    if guess_entry(entry, allow_seasonless=allow_seasonless, config=group_settings):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/series.py", line 43, in guess_entry
    allow_seasonless=allow_seasonless)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/plugin_parsing.py", line 70, in parse_series
    return parser.parse_series(data, name=name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_guessit.py", line 315, in parse_series
    guess_result = guessit_api.guessit(data, options=guessit_options)
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 71, in guessit
    string = string.encode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2013' in position 23: ordinal not in range(256)
sometimes it u'\u2013' u'\u2018' and u'\u2019'
But i have utf-8 everywhere activated, when i deactivate guessit, it works, but with your tool it works much better :)

**Comment by Toilal** [comment]
Should be fixed with 2.0.2 that i've just released.

**Comment by Toilal** [comment]
Please close after testing

**Comment by crack00r** [comment]
update guessit to 2.0.2
2016-01-30 11:30 CRITICAL task          premieren_en    BUG: Unhandled error in plugin series_premiere: 'latin-1' codec can't encode character u'\u2013' in position 23: ordinal not in range(256)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series_premiere.py", line 62, in on_task_metainfo
    if guess_entry(entry, allow_seasonless=allow_seasonless, config=group_settings):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/series.py", line 43, in guess_entry
    allow_seasonless=allow_seasonless)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/plugin_parsing.py", line 70, in parse_series
    return parser.parse_series(data, name=name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_guessit.py", line 315, in parse_series
    guess_result = guessit_api.guessit(data, options=guessit_options)
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 71, in guessit
    string = string.encode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2013' in position 23: ordinal not in range(256)

**Comment by Toilal** [comment]
I think i've done something wrong with the release, i'll have to ban 2.0.2
and release properly with 2.0.3...

**Comment by crack00r** [comment]
Ok, waiting for the update, and give it a try
right now --upgrade give me 2.0.2

**Comment by Toilal** [comment]
Release performed, should be ok now ! sorry about that, 2.0.2 has been removed.

**Comment by crack00r** [comment]
update to 2.0.3
1st run, looks good!
thx!

**Comment by Toilal** [comment]
This is an issue I have fixed yesterday, i'll perform a new release during
the day. You'll then have to upgrade your dependencies then and it'll be ok
!
