### ISSUE TITLE
[Flexget] guessit crash when id_regexps is defined

### ISSUE THREAD

**Issue by Toilal** [guessit-io/guessit#267]
I've just created this script, which configure guessit exactly like in current master of Flexget.

```python
from guessit.rules import rebulk_builder
from guessit.api import GuessItApi

from rebulk import Rebulk
from rebulk.pattern import RePattern

def _id_regexps_function(input_string, context):
    ret = []
    for regexp in context.get('id_regexps'):
        for match in RePattern(regexp, children=True).matches(input_string, context):
            ret.append(match.span)
    return ret

_id_regexps = Rebulk().functional(_id_regexps_function, name='regexpId', disabled=lambda context: not context.get('id_regexps'))

guessit_api = GuessItApi(rebulk_builder().rebulk(_id_regexps))

string="[HorribleSubs] Prince of Stride - Alternative - 05 [1080p].mkv"
options={u'allowed_languages': [u'en', u'fr'], 
u'name_only': True, 
'strict_name': True, 
u'episode_prefer_number': True, 
'alternate_names': [u'Triage X', u'\u30c8\u30ea\u30a2\u30fc\u30b8X'], 
u'sequence_regexps': [], 
u'date_regexps': [], 
'assume_special': None, 
'prefer_specials': True, 
'allow_groups': [], 
u'date_day_first': None, 
'identified_by': u'id', 
'name': u'Triage X', 
u'allowed_countries': [u'us', u'uk', u'gb'], 
'special_ids': [u'OAV', u'OVA', u'OAD', u'Special', u'Extra', u'.5'], 
u'date_year_first': None, 
'date_dayfirst': None, 
'date_yearfirst': None, 
'name_regexps': [], 
u'id_regexps': [u'(\\d\\d)-(\\d\\d)', u'(\\d\\d)*', u'(\\d*)', u'(\\d+) bluray', u'(Batch)', u'Vol(\\d*)-(\\d*)', u'Vol.(\\d\\d)', u'Vol.(\\d)', u'Vol.(\\d\\d\\d)', u'\\b(?:M{0,3})(?:D?C{0,3}|C[DM])(?:L?X{0,3}|X[LC])(?:V?I{0,3}|I[VX])(?=(\\.\\s|\\s|\\)|$))'], 
u'ep_regexps': [], 
u'type': u'episode'}

ret = guessit_api.guessit(string, options)
print(dict(ret))
```

And can reproduce the issue:

```
$ python2 test.py 
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    ret = guessit_api.guessit(string, options)
  File "/home/ralvergnat/idea-projects/guessit/guessit/api.py", line 113, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.0.dev0
string=[HorribleSubs] Prince of Stride - Alternative - 05 [1080p].mkv
options={u'name_only': True, 'strict_name': True, u'sequence_regexps': [], u'date_regexps': [], 'assume_special': None, 'identified_by': u'id', u'allowed_countries': [u'us', u'uk', u'gb'], 'date_yearfirst': None, 'name_regexps': [], u'ep_regexps': [], u'type': u'episode', u'allowed_languages': [u'en', u'fr'], u'episode_prefer_number': True, 'alternate_names': [u'Triage X', u'\u30c8\u30ea\u30a2\u30fc\u30b8X'], u'id_regexps': [u'(\\d\\d)-(\\d\\d)', u'(\\d\\d)*', u'(\\d*)', u'(\\d+) bluray', u'(Batch)', u'Vol(\\d*)-(\\d*)', u'Vol.(\\d\\d)', u'Vol.(\\d)', u'Vol.(\\d\\d\\d)', u'\\b(?:M{0,3})(?:D?C{0,3}|C[DM])(?:L?X{0,3}|X[LC])(?:V?I{0,3}|I[VX])(?=(\\.\\s|\\s|\\)|$))'], 'name': u'Triage X', 'prefer_specials': True, u'date_day_first': None, 'special_ids': [u'OAV', u'OVA', u'OAD', u'Special', u'Extra', u'.5'], u'date_year_first': None, 'date_dayfirst': None, 'allow_groups': []}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ralvergnat/idea-projects/guessit/guessit/api.py", line 102, in guessit
    matches = self.rebulk.matches(string, options)
  File "/home/ralvergnat/.pyenv/versions/2.7.11-guessit/lib/python2.7/site-packages/rebulk/rebulk.py", line 275, in matches
    self._execute_rules(matches, context)
  File "/home/ralvergnat/.pyenv/versions/2.7.11-guessit/lib/python2.7/site-packages/rebulk/rebulk.py", line 306, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/home/ralvergnat/.pyenv/versions/2.7.11-guessit/lib/python2.7/site-packages/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/home/ralvergnat/.pyenv/versions/2.7.11-guessit/lib/python2.7/site-packages/rebulk/rules.py", line 339, in execute_rule
    when_response = rule.when(matches, context)
  File "/home/ralvergnat/.pyenv/versions/2.7.11-guessit/lib/python2.7/site-packages/rebulk/processors.py", line 56, in when
    conflicting_matches = matches.conflicting(match)
  File "/home/ralvergnat/.pyenv/versions/2.7.11-guessit/lib/python2.7/site-packages/rebulk/match.py", line 388, in conflicting
    ret.remove(match)
ValueError: list.remove(x): x not in list
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
```

**Comment by Toilal** [comment]
Fixed in rebulk
