### ISSUE TITLE
Pyinstaller with guessit not working

### ISSUE THREAD

**Issue by jimsawan** [guessit-io/guessit#27]
I Used pyinstaller 2.0 to create an executable for this small piece of code. However, when I run the executable, I get the following error:

Traceback (most recent call last):
  File "<string>", line 3, in main
  File "C:\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "C:\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
    exec co in mod.__dict__
  File "C:\pyinstaller-2.0\guessittest\build\pyi.win32\guessittest\out00-PYZ.pyz
\guessit", line 74, in <module>
  File "C:\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "C:\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
    exec co in mod.__dict__
  File "C:\pyinstaller-2.0\guessittest\build\pyi.win32\guessittest\out00-PYZ.pyz
\guessit.guess", line 23, in <module>
  File "C:\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "C:\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
    exec co in mod.__dict__
  File "C:\pyinstaller-2.0\guessittest\build\pyi.win32\guessittest\out00-PYZ.pyz\guessit.language", line 24, in <module>
  File "C:\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "C:\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
    exec co in mod.__dict__
  File "C:\pyinstaller-2.0\guessittest\build\pyi.win32\guessittest\out00-PYZ.pyz\guessit.language", line 24, in <module>
  File "C:\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "C:\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
    exec co in mod.__dict__
  File "C:\pyinstaller-2.0\guessittest\build\pyi.win32\guessittest\out00-PYZ.pyz\guessit.country", line 37, in <module>
  File "C:\pyinstaller-2.0\guessittest\build\pyi.win32\guessittest\out00-PYZ.pyz\guessit.fileutils", line 87, in load_file_in_same_dir
IOError: [Errno 22] invalid mode ('r') or filename: u'C:\pyinstaller-2.0\guessittest\dist\guessittest.exe?199168\guessit\ISO-3166-1_utf8.txt'

The code I am using is the following:

def main():
    try:
        import guessit
    except:
        import traceback
    os.system('PAUSE')
if **name** == '**main**':
    main()

So, what do you think is the problem?

**Comment by Toilal** [comment]
This gonna happen really soon :p
