### ISSUE TITLE
Sandbox Violation during install using pip?

### ISSUE THREAD

**Issue by sharperer** [guessit-io/guessit#271]
Attempting to install guessit as a component of Flexget however pip is raising the following error:

      `File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 185, in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: open('/usr/local/lib/python2.7/site-packages/test-easy-install-19390.write-test', 'w') {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.`

Any help would be much appreciated!

**Comment by Toilal** [comment]
Do you run pip or easy_install ?

**Comment by sharperer** [comment]
pip although I also tried using easy_install after it failed with a similar result.  Here's the full error:

`DiskStation> pip install guessit
Collecting guessit
  Using cached guessit-2.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-unls_V/guessit/setup.py", line 78, in <module>
        setup(**args)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 576, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 821, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 833, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 294, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 585, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 615, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 805, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1082, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1071, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 30, in run_setup
        lambda: execfile(
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 72, in run
        return func()
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 32, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 56, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules'
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 576, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 821, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 833, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 292, in fetch_build_egg
        cmd.ensure_finalized()
      File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 270, in finalize_options
        if not self.editable: self.check_site_dir()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 399, in check_site_dir
        open(testfile,'w').close()
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in _open
        self._violation("open", path, mode, *args, **kw)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 185, in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: open('/usr/local/lib/python2.7/site-packages/test-easy-install-27487.write-test', 'w') {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.`

**Comment by rhullah** [comment]
I'm having the same issue.  Any progress on this?

**Comment by Toilal** [comment]
I can't reproduce, sorry.

**Comment by rhullah** [comment]
Once I rebuilt my Python environment it worked for me. So probably something wrong with my environment.
