### ISSUE TITLE
Flexget: TypeError: expected a character buffer object

### ISSUE THREAD

**Issue by stevezau** [guessit-io/guessit#280]
Hey,

We are in the middle of enabling py3 support on flexget.. We have all test passing in flexget on py3 and only 1 failing on py2 which is this one... (see below)

We are using http://python-future.org/

```   guess_result = guessit_api.guessit(data, options=guessit_options) ```

data = http://python-future.org/_modules/future/types/newstr.html

I'm not sure if this is something that should be fixed in guessit or the flexget guessit parser?

```
F
self = <tests.test_series.TestBacklog object at 0x10aa47790>
manager = <tests.conftest.MockManager object at 0x10aa55d50>
execute_task = <function execute at 0x10aa868c0>

    def testBacklog(self, manager, execute_task):
        """Series plugin: backlog"""
        task = execute_task('backlog')
        assert task.entries and not task.accepted, 'no entries at the start'
        # simulate test going away from the task
        del (manager.config['tasks']['backlog']['mock'])
        age_series(hours=12)
>       task = execute_task('backlog')

test_series.py:1405: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
conftest.py:84: in execute
    task.execute()
../flexget/task.py:77: in wrapper
    return func(self, *args, **kw)
../flexget/task.py:586: in execute
    self._execute()
../flexget/task.py:552: in _execute
    self.__run_task_phase(phase)
../flexget/task.py:415: in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
../flexget/task.py:477: in __run_plugin
    self.manager.crash_report()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.conftest.MockManager object at 0x10aa55d50>

    def crash_report(self):
        # We don't want to silently swallow crash reports during unit tests
        log.error('Crash Report Traceback:', exc_info=True)
>       raise CrashReport('Crash report created during unit test, check log for traceback.')
E       CrashReport: Crash report created during unit test, check log for traceback.

conftest.py:249: CrashReport
--------------------------------- Captured log ---------------------------------
manager.py                 111 INFO     last manager was not torn down correctly
manager.py                 160 DEBUG    sys.defaultencoding: ascii
manager.py                 161 DEBUG    sys.getfilesystemencoding: utf-8
manager.py                 162 DEBUG    os.path.supports_unicode_filenames: True
conftest.py                221 DEBUG    database_uri: sqlite:///:memory:
plugin.py                  375 DEBUG    Trying to load plugins from: [u'/Users/sadams/Workspace/plugins', '/Users/sadams/Workspace/Flexget/flexget/plugins']
plugin.py                  396 DEBUG    Plugin `memusage` requires `ext lib `guppy`` to load.
plugin.py                  441 DEBUG    Plugins took 0.05 seconds to load
manager.py                 656 DEBUG    Connecting to: sqlite:///:memory:
db_schema.py                58 DEBUG    Initializing plugin feed schema version to 0
db_schema.py                58 DEBUG    Initializing plugin api_trakt schema version to 3
db_schema.py                58 DEBUG    Initializing plugin make_rss schema version to 0
db_schema.py                58 DEBUG    Initializing plugin series schema version to 12
db_schema.py                58 DEBUG    Initializing plugin discover schema version to 0
db_schema.py                58 DEBUG    Initializing plugin seen schema version to 4
db_schema.py                58 DEBUG    Initializing plugin pogcal_acquired schema version to 0
db_schema.py                58 DEBUG    Initializing plugin archive schema version to 0
db_schema.py                58 DEBUG    Initializing plugin digest schema version to 0
db_schema.py                58 DEBUG    Initializing plugin remember_rejected schema version to 3
db_schema.py                58 DEBUG    Initializing plugin queue schema version to 2
db_schema.py                58 DEBUG    Initializing plugin simple_persistence schema version to 2
db_schema.py                58 DEBUG    Initializing plugin myepisodes schema version to 0
db_schema.py                58 DEBUG    Initializing plugin delay schema version to 1
db_schema.py                58 DEBUG    Initializing plugin failed schema version to 3
db_schema.py                58 DEBUG    Initializing plugin tail schema version to 0
db_schema.py                58 DEBUG    Initializing plugin api_tvdb schema version to 4
db_schema.py                58 DEBUG    Initializing plugin subtitle_queue schema version to 0
db_schema.py                58 DEBUG    Initializing plugin movie_queue schema version to 4
db_schema.py                58 DEBUG    Initializing plugin torrent411 schema version to 0
db_schema.py                58 DEBUG    Initializing plugin api_tmdb schema version to 1
db_schema.py                58 DEBUG    Initializing plugin log_once schema version to 0
db_schema.py                58 DEBUG    Initializing plugin imdb_lookup schema version to 7
db_schema.py                58 DEBUG    Initializing plugin api_rottentomatoes schema version to 2
db_schema.py                58 DEBUG    Initializing plugin version_checker schema version to 0
db_schema.py                58 DEBUG    Initializing plugin telegram_chat_ids schema version to 0
db_schema.py                58 DEBUG    Initializing plugin t411 schema version to 0
db_schema.py                58 DEBUG    Initializing plugin input_cache schema version to 0
db_schema.py                58 DEBUG    Initializing plugin import_series schema version to 0
db_schema.py                58 DEBUG    Initializing plugin tvmaze schema version to 3
db_schema.py                58 DEBUG    Initializing plugin thetvdb_favorites schema version to 0
db_schema.py                58 DEBUG    Initializing plugin rutracker_auth schema version to 0
db_schema.py                58 DEBUG    Initializing plugin backlog schema version to 1
manager.py                 593 DEBUG    New config data loaded.
plugin_parsing.py           31 DEBUG    setting default movie parser to internal. (options: {u'internal': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x10660a150>, u'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x1076e5590>})
plugin_parsing.py           31 DEBUG    setting default series parser to internal. (options: {u'internal': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x10660a150>, u'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x1076e5590>})
conftest.py                 75 INFO     ********** Running task: backlog ********** 
task.py                    501 DEBUG    executing backlog
plugin_template.py          91 DEBUG    Merging template global into task backlog
series.py                 1638 DEBUG    adding series test into db
series.py                 1643 DEBUG    -> added <Series(id=1,name=test)>
backlog.py                 167 DEBUG    0 entries purged from backlog
logger.py                  142 VERBOSE  Produced 1 entries.
parser_guessit.py          303 DEBUG    Parsing series: `Test.S01E01.hdtv-FlexGet` [options: {'identified_by': u'auto', u'date_regexps': [], 'strict_name': False, 'name': u'test', 'prefer_specials': None, 'special_ids': [], 'alternate_names': [], u'sequence_regexps': [], 'date_dayfirst': None, u'id_regexps': [], 'assume_special': None, 'name_regexps': [], 'date_yearfirst': None, 'allow_groups': [], u'ep_regexps': []}]
parser_common.py           183 DEBUG    NAME SUCCESS: ^(?:(?:\[[^\[\]]*\])|(?:HD.720p?:)|(?:HD.1080p?:))?(?:[^\w&]|_)*(test)(?:\b|_)(?:[^\w&]|_)* matched to Test.S01E01.hdtv-FlexGet
parser_guessit.py          320 DEBUG    Parsing result: <GuessitParsedSerie(name=test,id=1,season=1,episode=1,quality=hdtv,proper=0,status=OK)> (in 9.21200000001 ms)
series.py                 1250 DEBUG    Test.S01E01.hdtv-FlexGet detected as <GuessitParsedSerie(name=test,id=1,season=1,episode=1,quality=hdtv,proper=0,status=OK)>, field: title
series.py                  635 DEBUG    adding episode S01E01 into series test
series.py                  647 DEBUG    -> added <Episode(id=None,identifier=S01E01,season=1,number=1)>
series.py                  662 DEBUG    adding release <GuessitParsedSerie(name=test,id=1,season=1,episode=1,quality=hdtv,proper=0,status=OK)> into episode
series.py                  668 DEBUG    -> added <Release(id=None,quality=hdtv,downloaded=None,proper_count=0,title=Test.S01E01.hdtv-FlexGet)>
series.py                  522 DEBUG    test episode type totals: {u'ep': 1}
logger.py                  142 VERBOSE  identified by is currently on `auto` for test. Multiple id types may be accepted until it locks in on the appropriate type.
series.py                 1188 DEBUG    identified_by set to 'auto' based on series history
series.py                 1272 DEBUG    start with episodes: [u'Test.S01E01.hdtv-FlexGet']
series.py                 1287 DEBUG    current episodes: [u'Test.S01E01.hdtv-FlexGet']
series.py                 1301 DEBUG    -------------------- process_propers -->
series.py                 1422 DEBUG    propers - downloaded qualities: {}
series.py                 1344 DEBUG    continuing w. episodes: [u'Test.S01E01.hdtv-FlexGet']
series.py                 1345 DEBUG    best episode is: Test.S01E01.hdtv-FlexGet
series.py                 1352 DEBUG    -------------------- episode tracking -->
series.py                  572 DEBUG    get_latest_release returning None, no downloaded episodes found for: test
series.py                 1484 DEBUG    latest download: None
series.py                 1485 DEBUG    current: <Episode(id=1,identifier=S01E01,season=1,number=1)>
series.py                 1520 DEBUG    timeframe: 6 hours
series.py                 1531 DEBUG    timeframe: 6:00:00, first_seen: 2016-03-10 09:46:22.353395, expires: 2016-03-10 15:46:22.353395
series.py                 1547 INFO     Timeframe waiting test for 5h:59min, currently best is Test.S01E01.hdtv-FlexGet
backlog.py                 136 DEBUG    Saving Test.S01E01.hdtv-FlexGet
plugin_urlrewriting.py      29 DEBUG    Checking 0 entries
logger.py                  142 VERBOSE  Summary - Accepted: 0 (Rejected: 0 Undecided: 1 Failed: 0)
series.py                 1599 DEBUG    on_task_learn
simple_persistence.py      130 DEBUG    Flushing simple persistence for task backlog to db.
conftest.py                 75 INFO     ********** Running task: backlog ********** 
task.py                    501 DEBUG    executing backlog
plugin_template.py          91 DEBUG    Merging template global into task backlog
remember_rejected.py        87 DEBUG    Task config has changed since last run, purging remembered entries.
backlog.py                 160 DEBUG    Restoring Test.S01E01.hdtv-FlexGet
logger.py                  142 VERBOSE  Added 1 entries from backlog
backlog.py                 167 DEBUG    1 entries purged from backlog
logger.py                  142 VERBOSE  Produced 1 entries.
parser_guessit.py          303 DEBUG    Parsing series: `Test.S01E01.hdtv-FlexGet` [options: {'identified_by': u'auto', u'date_regexps': [], 'strict_name': False, 'name': u'test', 'prefer_specials': None, 'special_ids': [], 'alternate_names': [], u'sequence_regexps': [], 'date_dayfirst': None, u'id_regexps': [], 'assume_special': None, 'name_regexps': [], 'date_yearfirst': None, 'allow_groups': [], u'ep_regexps': []}]
task.py                    476 CRITICAL BUG: Unhandled error in plugin series: An internal error has occured in guessit.\n===================== Guessit Exception Report =====================\nversion=2.0.4\nstring=b'Test.S01E01.hdtv-FlexGet'\noptions={u'allowed_languages': [u'en', u'fr'], u'name_only': True, 'strict_name': False, u'episode_prefer_number': True, u'expected_title': [u're:test'], 'alternate_names': [], u'sequence_regexps': [], u'date_regexps': [], 'assume_special': None, 'prefer_specials': None, 'allow_groups': [], u'date_day_first': None, 'identified_by': u'auto', 'name': u'test', u'allowed_countries': [u'us', u'uk', u'gb'], 'special_ids': [], u'date_year_first': None, 'date_dayfirst': None, 'date_yearfirst': None, 'name_regexps': [], u'id_regexps': [], u'ep_regexps': [], u'type': u'episode'}\n--------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/guessit/api.py", line 102, in guessit\n    matches = self.rebulk.matches(string, options)\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rebulk/rebulk.py", line 273, in matches\n    self._matches_patterns(matches, context)\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rebulk/rebulk.py", line 336, in _matches_patterns\n    pattern_matches = pattern.matches(matches.input_string, context)\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rebulk/pattern.py", line 172, in matches\n    for match in self._match(pattern, input_string, context):\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rebulk/pattern.py", line 371, in _match\n    ret = call(pattern, input_string, context, **self._kwargs)\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rebulk/loose.py", line 50, in call\n    return function(*call_args, **call_kwargs)\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/guessit/rules/markers/groups.py", line 33, in mark_groups\n    start_type = starting.find(char)\nTypeError: expected a character buffer object\n--------------------------------------------------------------------\nPlease report at https://github.com/guessit-io/guessit/issues.\n====================================================================
conftest.py                248 ERROR    Crash Report Traceback:
Traceback (most recent call last):
  File "/Users/sadams/Workspace/Flexget/flexget/task.py", line 445, in __run_plugin
    return method(*args, **kwargs)
  File "/Users/sadams/Workspace/Flexget/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/Users/sadams/Workspace/Flexget/flexget/plugins/filter/series.py", line 1129, in on_task_metainfo
    self.parse_series(task.entries, series_name, series_config)
  File "/Users/sadams/Workspace/Flexget/flexget/plugins/filter/series.py", line 1245, in parse_series
    parsed = get_plugin_by_name('parsing').instance.parse_series(entry['title'], name=series_name, **params)
  File "/Users/sadams/Workspace/Flexget/flexget/plugins/parsers/plugin_parsing.py", line 73, in parse_series
    return parser.parse_series(data, name=name, **kwargs)
  File "/Users/sadams/Workspace/Flexget/flexget/plugins/parsers/parser_guessit.py", line 317, in parse_series
    guess_result = guessit_api.guessit(data, options=guessit_options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/guessit/api.py", line 113, in guessit
    raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.0.4
string=b'Test.S01E01.hdtv-FlexGet'
options={u'allowed_languages': [u'en', u'fr'], u'name_only': True, 'strict_name': False, u'episode_prefer_number': True, u'expected_title': [u're:test'], 'alternate_names': [], u'sequence_regexps': [], u'date_regexps': [], 'assume_special': None, 'prefer_specials': None, 'allow_groups': [], u'date_day_first': None, 'identified_by': u'auto', 'name': u'test', u'allowed_countries': [u'us', u'uk', u'gb'], 'special_ids': [], u'date_year_first': None, 'date_dayfirst': None, 'date_yearfirst': None, 'name_regexps': [], u'id_regexps': [], u'ep_regexps': [], u'type': u'episode'}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/guessit/api.py", line 102, in guessit
    matches = self.rebulk.matches(string, options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rebulk/rebulk.py", line 273, in matches
    self._matches_patterns(matches, context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rebulk/rebulk.py", line 336, in _matches_patterns
    pattern_matches = pattern.matches(matches.input_string, context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rebulk/pattern.py", line 172, in matches
    for match in self._match(pattern, input_string, context):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rebulk/pattern.py", line 371, in _match
    ret = call(pattern, input_string, context, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rebulk/loose.py", line 50, in call
    return function(*call_args, **call_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/guessit/rules/markers/groups.py", line 33, in mark_groups
    start_type = starting.find(char)
TypeError: expected a character buffer object
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================

```

**Comment by gazpachoking** [comment]
@Toilal Hmm, was looking at this a bit (didn't get to the root of the problem yet though.) I was just wondering the reasoning behind only [operating on bytes](https://github.com/guessit-io/guessit/blob/master/guessit/api.py#L96-L98) in py2? My inclination would be to only operate on text on either platform (maybe explicitly decoding bytes to text with ascii on py2, like the default python behavior.)

**Comment by Toilal** [comment]
I've made the choice to always operate with "default" string in python 2 and python 3. Guessit and rebulk are now designed with this in mind, because trying to support both str and unicode objects everywhere in both projects was really painfull.

So internally, guessit and rebulk only deals with ```str``` objects. But guessit API facade performs the conversion if required so it works nicely with either ```str``` or ```unicode``` objects, in any python version. Note that with this pattern, there's no need of ```__future__.unicode_literals``` at all.

[As you can see here](https://github.com/guessit-io/guessit/blob/master/guessit/api.py#L96-L110), if input is converted, it will be converted back before returning the final result. Internally, guessit only works with ```str``` objects, but for user it just works with anything.

So about this particular issue, you try to input python-future `future.types.newstr` to guessit. It seems it's not converted by guessit API facade, because it seems to be neither instance of ```str``` nor ```unicode```.

Try converting input data ```newstr``` to default ```str``` object before calling the API function.

Good job anyway for going for python 3 ! It's a good step forward.

**Comment by stevezau** [comment]
We solved it with future.utils.native
