### ISSUE TITLE
UnicodeDecodeError since options are not handled the same way as input_string

### ISSUE THREAD

**Issue by ratoaq2** [guessit-io/guessit#326]
While working on Python 2/3 compatibility, I found this issue:

In Python 2, guessit converts `input_string` to a non-unicode string (https://github.com/guessit-io/guessit/blob/a18f827b45cb6495dd3f340e1d2030b7ebe67830/guessit/api.py#L96)

But guessit doesn't convert the `options` (expected_titles, expected_groups, etc...) leading to the following error:

```
Error
Traceback (most recent call last):
  File "/home/user/workspace/git/SickRage/lib/nose_parameterized/parameterized.py", line 365, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/user/workspace/git/SickRage/tests/guessit_tests.py", line 89, in test_guess
    actual = parser.guess(release_name, show_type=options.get('show_type'))
  File "/home/user/workspace/git/SickRage/sickbeard/name_parser/guessit_parser.py", line 104, in guess
    return guessit.guessit(name, options=options)
  File "/home/user/workspace/git/SickRage/lib/guessit/api.py", line 54, in guessit
    return default_api.guessit(string, options)
  File "/home/user/workspace/git/SickRage/lib/guessit/api.py", line 113, in guessit
    raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.0.dev0
string=Show Name - Temporada 4 [HDTV][Cap.408][Español Castellano]
options={'allowed_languages': [u'ru', u'hu', u'en', u'nl', u'pt', u'de', u'jp', u'sv', u'it', u'fr', u'es', u'uk', u'ro', u'pl', u'he'], 'expected_group': [u're:\\bCDD\\b', u're:\\bF4ST3R\\b', u're:\\bTGNF4ST\\b', u're:\\bNovaRip\\b', u're:\\bRiPRG\\b', u're:\\bPtM\\b', u're:\\bbyEMP\\b', u're:\\b4EVERHD\\b', u're:\\bPOURMOi\\b', u're:\\bPARTiCLE\\b', u're:\\bTV2LAX9\\b', u're:\\bCDP\\b', u're:\\bELITETORRENT\\b', u're:\\bRipPourBox\\b', u're:\\bF4ST\\b', u're:\\bHDD\\b'], 'expected_title': [u're:(?<![^/\\\\])60 Minutes\\b', u'11.22.63', u're:(?<![^/\\\\])500 Bus Stops\\b', u're:(?<![^/\\\\])Star Trek DS9\\b', u're:(?<![^/\\\\])12 Monkeys\\b', u're:(?<![^/\\\\])The 100\\b', u're:(?<![^/\\\\])\\w+ it\\b'], 'allowed_countries': [u'gb', u'us'], 'episode_prefer_number': False, 'show_type': None, 'type': u'episode', 'implicit': True}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/workspace/git/SickRage/lib/guessit/api.py", line 102, in guessit
    matches = self.rebulk.matches(string, options)
  File "/home/user/workspace/git/SickRage/lib/rebulk/rebulk.py", line 273, in matches
    self._matches_patterns(matches, context)
  File "/home/user/workspace/git/SickRage/lib/rebulk/rebulk.py", line 336, in _matches_patterns
    pattern_matches = pattern.matches(matches.input_string, context)
  File "/home/user/workspace/git/SickRage/lib/rebulk/pattern.py", line 173, in matches
    for match in self._match(pattern, input_string, context):
  File "/home/user/workspace/git/SickRage/lib/rebulk/pattern.py", line 380, in _match
    ret = call(pattern, input_string, context, **self._kwargs)
  File "/home/user/workspace/git/SickRage/lib/rebulk/loose.py", line 50, in call
    return function(*call_args, **call_kwargs)
  File "/home/user/workspace/git/SickRage/lib/guessit/rules/properties/title.py", line 47, in expected_title
    for start in find_all(input_string, search, ignore_case=True):
  File "/home/user/workspace/git/SickRage/lib/rebulk/utils.py", line 48, in find_all
    start = string.find(sub, start, end)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 44: ordinal not in range(128)
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
```

**Comment by Toilal** [comment]
Nice catch, thanks !

**Comment by ratoaq2** [comment]
A quick question: Shouldn't guessit convert all these strings to unicode in python2?

**Comment by Toilal** [comment]
No I think those options should be handled as default python 2 str objets,
just like filename input.

**Comment by ratoaq2** [comment]
Hi Toilal, I had this issue using guessit as an API (not command line). 

I haven't tested the fix yet, but I'll let you know the results. 

Btw, thanks for such nice work

**Comment by Toilal** [comment]
Thanks ! :) It should work, I just removed some unicode conversion code that was here before the str py2/3 refactoring.

**Comment by ratoaq2** [comment]
I still have issues with it

```
   raise GuessitException(string, options)
   GuessitException: An internal error has occured in guessit.
   ===================== Guessit Exception Report =====================
   version=2.1.1.dev0
   string=Show.Name.-.Temporada1.[HDTV][Cap.105][Español]
   options={'allowed_languages': ['ru', 'hu', 'en', 'nl', 'pt', 'de', 'jp', 'sv', 'it', 'fr', 'es', 'uk', 'ro', 'pl', 'he'], 'expected_group': ['re:\\bF4ST3R\\b', 're:\\bTGNF4ST\\b', 're:\\bNovaRip\\b', 're:\\bRiPRG\\b', 're:\\bPtM\\b', 're:\\bbyEMP\\b', 're:\\b4EVERHD\\b', 're:\\bPOURMOi\\b', 're:\\bPARTiCLE\\b', 're:\\bTV2LAX9\\b', 're:\\bELITETORRENT\\b', 're:\\bRipPourBox\\b', 're:\\bF4ST\\b', 're:\\bHDD\\b'], 'expected_title': [u're:(?<![^/\\\\])\\w+ it\\b', u'1.2.3', u're:(?<![^/\\\\\\.])1 +2 +3(?=[\\W_]|$)', u'11.22.63', u're:(?<![^/\\\\\\.])11 +22 +63(?=[\\W_]|$)', u're:(?<![^/\\\\\\.])12 +Monkeys(?=[\\W_]|$)', u're:(?<![^/\\\\\\.])222 +Show(?=[\\W_]|$)', u're:(?<![^/\\\\\\.])500 +Bus +Stops(?=[\\W_]|$)', u're:(?<![^/\\\\\\.])60 +Minutes(?=[\\W_]|$)', u're:(?<=[\\W_])Mobile +Suit +Gundam +UC +RE ?0096(?=[\\W_]|$)', u're:(?<=[\\W_])Mobile +Suit +Gundam +Unicorn +RE +0096(?=[\\W_]|$)', u're:(?<![^/\\\\\\.])R +15(?=[\\W_]|$)', u're:(?<=[\\W_])The +10 +Anime +Show(?=[\\W_]|$)', u're:(?<![^/\\\\\\.])The +100(?=[\\W_]|$)', u're:(?<![^/\\\\\\.])The +123 +Show(?=[\\W_]|$)', u"re:(?<![^/\\\\\\.])The +Someone'?s +Show +2(?=[\\W_]|$)", u're:(?<![^/\\\\\\.])3 +Show +p.+ +abc2(?=[\\W_]|$)', u"re:(?<![^/\\\\\\.])Show +'?70s +Name(?=[\\W_]|$)", u're:(?<=[\\W_])An +Anime +Show +100(?=[\\W_]|$)'], 'allowed_countries': ['gb', 'us'], 'episode_prefer_number': False, 'type': u'episode', 'implicit': True}
   --------------------------------------------------------------------
   Traceback (most recent call last):
     File "/home/user/workspace/git/SickRage/lib/guessit/api.py", line 102, in guessit
       matches = self.rebulk.matches(string, options)
     File "/home/user/workspace/git/SickRage/lib/rebulk/rebulk.py", line 273, in matches
       self._matches_patterns(matches, context)
     File "/home/user/workspace/git/SickRage/lib/rebulk/rebulk.py", line 336, in _matches_patterns
       pattern_matches = pattern.matches(matches.input_string, context)
     File "/home/user/workspace/git/SickRage/lib/rebulk/pattern.py", line 174, in matches
       for match in self._match(pattern, input_string, context):
     File "/home/user/workspace/git/SickRage/lib/rebulk/pattern.py", line 384, in _match
       ret = call(pattern, input_string, context, **self._kwargs)
     File "/home/user/workspace/git/SickRage/lib/rebulk/loose.py", line 50, in call
       return function(*call_args, **call_kwargs)
     File "/home/user/workspace/git/SickRage/lib/guessit/rules/properties/title.py", line 47, in expected_title
       for start in find_all(input_string, search, ignore_case=True):
     File "/home/user/workspace/git/SickRage/lib/rebulk/utils.py", line 48, in find_all
       start = string.find(sub, start, end)
   UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)
   --------------------------------------------------------------------
   Please report at https://github.com/guessit-io/guessit/issues.
   ====================================================================
```


I have a python file with:
```
from __future__ import unicode_literals

# with some fields like these:
fixed_expected_titles = {
    # guessit: conflicts with italian language
    r're:(?<![^/\\])\w+ it\b',
}

# And I call guessit like this
    final_options.update(dict(type='episode', implicit=True,
                              episode_prefer_number=final_options.get('show_type') == 'anime',
                              expected_title=get_expected_titles(sickbeard.showList),
                              expected_group=expected_groups,
                              allowed_languages=allowed_languages,
                              allowed_countries=allowed_countries))
    return guessit.guessit(name, options=final_options)
```

The same treatment you execute for the input string here: https://github.com/guessit-io/guessit/blob/a18f827b45cb6495dd3f340e1d2030b7ebe67830/guessit/api.py#L96-L101, you should execute all options.

If I do that on my code, then it fixes the issue

**Comment by Toilal** [comment]
When running python 2,options should be native str objects. So please
remove the future unicode_literals import.

**Comment by Toilal** [comment]
Would be great to reproduce in a standalone script :)

**Comment by Toilal** [comment]
I can definitively reproduce the issue

* Crash reproduced *
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from guessit import guessit

guessit("Show.Name.-.Temporada1.[HDTV][Cap.105][Español]", 
        options={"expected_title": ["Español"]})
```

* Does not crash *
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from guessit import guessit

guessit("Show.Name.-.Temporada1.[HDTV][Cap.105][Español]", 
        options={"expected_title": ["Español"]})
```

* Does not crash too *
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from guessit import guessit

guessit(b"Show.Name.-.Temporada1.[HDTV][Cap.105][Español]", 
        options={"expected_title": [b"Español"]})
```

**Comment by Toilal** [comment]
But i'll try to add same string conversion than input string for options to avoid this issue.

**Comment by ratoaq2** [comment]
You were too fast, I'll test the changes now. But I would like to put a note:

Like the input string, the options can also come from other places (not only from a list in that python file) and I cannot always ensure that they are compliant. Since guessit already handles the input string, it should also handle the options the same way, just to be consistent. Or not handle them at all, and also skip the input string. So the "conversion" happens either outside guessit or inside guessit.

**Comment by ratoaq2** [comment]
Now it works like a charm :-)
