### ISSUE TITLE
guessit index out of range

### ISSUE THREAD

**Issue by deadc0de6** [guessit-io/guessit#390]
command line:
```
subliminal --addic7ed XXX XXX --opensubtitles XXX XXX download -p addic7ed -p opensubtitles -p podnapisi -w 10 -m 70 XXX
```

as reported by subliminal
```
===================== Guessit Exception Report =====================
version=2.1.1
string=Lethal Weapon 2 ()
options={'type': 'movie'}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/usr/local/lib/python2.7/dist-packages/guessit/rules/processors.py", line 222, in then
    if match.raw[0] in seps_no_groups and (len(match.raw) < 3 or match.raw[2] not in seps_no_groups):
IndexError: string index out of range
```

**Comment by Toilal** [comment]
This issue is fixed with this commit : https://github.com/guessit-io/guessit/commit/956953878e773b8f4e8cede272725c2ddc9d3c95

It's available in develop branch.
