### ISSUE TITLE
An internal error has occurred in guessit

### ISSUE THREAD

**Issue by OmgImAlexis** [guessit-io/guessit#397]
I also noticed `occured` is missing an `r`.

```
2017-01-06 21:21:13 ERROR    SEARCHQUEUE-BACKLOG-281708 :: [DOGnzb] :: [ab588dc] Unknown exception while searching DOGnzb. Error: 'An internal error has occured in guessit.\n===================== Guessit Exception Report =====================\nversion=2.1.2.dev0\nstring=Body.of.Proof.S01E02.HDTV.XviD.2HD.720p.HDTV.X264\noptions={\'allowed_languages\': set([\'ru\', \'hu\', \'en\', \'nl\', \'pt\', \'de\', \'jp\', \'sv\', \'it\', \'fr\', \'es\', \'uk\', \'ro\', \'pl\', \'he\']), \'expected_group\': [\'TV2LAX9\', \'S4L\', \'DHD\'], \'expected_title\': [\'11.22.63\', \'12 Monkeys\', \'The 100\', \'Sense8\', \'2 Broke Girls\', \'Hawaii Five-0\', "Don\'t Trust the B---- in Apartment 23"], \'allowed_countries\': set([\'gb\', \'us\']), \'episode_prefer_number\': False, \'show_type\': \'normal\', \'type\': \'episode\', \'implicit\': True}\n--------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/app/sickrage/lib/guessit/api.py", line 120, in guessit\n    matches = self.rebulk.matches(string, options)\n  File "/app/sickrage/lib/rebulk/rebulk.py", line 288, in matches\n    self._execute_rules(matches, context)\n  File "/app/sickrage/lib/rebulk/rebulk.py", line 319, in _execute_rules\n    rules.execute_all_rules(matches, context)\n  File "/app/sickrage/lib/rebulk/rules.py", line 318, in execute_all_rules\n    when_response = execute_rule(rule, matches, context)\n  File "/app/sickrage/lib/rebulk/rules.py", line 343, in execute_rule\n    rule.then(matches, when_response, context)\n  File "/app/sickrage/lib/rebulk/rules.py", line 127, in then\n    cons.then(matches, when_response, context)\n  File "/app/sickrage/lib/rebulk/rules.py", line 140, in then\n    matches.remove(match)\n  File "/usr/lib/python2.7/_abcoll.py", line 689, in remove\n    del self[self.index(value)]\n  File "/app/sickrage/lib/rebulk/match.py", line 559, in __delitem__\n    self._remove_match(match)\n  File "/app/sickrage/lib/rebulk/match.py", line 133, in _remove_match\n    _BaseMatches._base_remove(self._tag_dict[tag], match)\nValueError: list.remove(x): x not in list\n--------------------------------------------------------------------\nPlease report at https://github.com/guessit-io/guessit/issues.\n===================================================================='
Traceback (most recent call last):
  File "/app/sickrage/medusa/search/core.py", line 522, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/app/sickrage/medusa/providers/generic_provider.py", line 217, in find_search_results
    parse_result = NameParser(parse_method=('normal', 'anime')[show.is_anime]).parse(title)
  File "/app/sickrage/medusa/name_parser/parser.py", line 232, in parse
    result = self._parse_string(name)
  File "/app/sickrage/medusa/name_parser/parser.py", line 63, in _parse_string
    guess = guessit.guessit(name, dict(show_type=self.show_type))
  File "/app/sickrage/medusa/name_parser/guessit_parser.py", line 73, in guessit
    result = default_api.guessit(name, options=final_options)
  File "/app/sickrage/lib/guessit/api.py", line 131, in guessit
    raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.2.dev0
string=Body.of.Proof.S01E02.HDTV.XviD.2HD.720p.HDTV.X264
options={'allowed_languages': set(['ru', 'hu', 'en', 'nl', 'pt', 'de', 'jp', 'sv', 'it', 'fr', 'es', 'uk', 'ro', 'pl', 'he']), 'expected_group': ['TV2LAX9', 'S4L', 'DHD'], 'expected_title': ['11.22.63', '12 Monkeys', 'The 100', 'Sense8', '2 Broke Girls', 'Hawaii Five-0', "Don't Trust the B---- in Apartment 23"], 'allowed_countries': set(['gb', 'us']), 'episode_prefer_number': False, 'show_type': 'normal', 'type': 'episode', 'implicit': True}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/sickrage/lib/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/app/sickrage/lib/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/app/sickrage/lib/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/app/sickrage/lib/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/app/sickrage/lib/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/app/sickrage/lib/rebulk/rules.py", line 127, in then
    cons.then(matches, when_response, context)
  File "/app/sickrage/lib/rebulk/rules.py", line 140, in then
    matches.remove(match)
  File "/usr/lib/python2.7/_abcoll.py", line 689, in remove
    del self[self.index(value)]
  File "/app/sickrage/lib/rebulk/match.py", line 559, in __delitem__
    self._remove_match(match)
  File "/app/sickrage/lib/rebulk/match.py", line 133, in _remove_match
    _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
```

**Comment by ratoaq2** [comment]
This issue is not related to guessit. Fixed in the correct repo
