### ISSUE TITLE
guessit exception

### ISSUE THREAD

**Issue by dima-vy** [guessit-io/guessit#463]
Got a following exception:
===================== Guessit Exception Report =====================
version=2.1.1
string= National Treasure Book of Secrets (2007).DiAMOND.[]
options={'type': 'movie'}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/lib/python2.7/site-packages/guessit-2.1.1-py2.7.egg/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/opt/lib/python2.7/site-packages/rebulk-0.8.2-py2.7.egg/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/opt/lib/python2.7/site-packages/rebulk-0.8.2-py2.7.egg/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/opt/lib/python2.7/site-packages/rebulk-0.8.2-py2.7.egg/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/opt/lib/python2.7/site-packages/rebulk-0.8.2-py2.7.egg/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/opt/lib/python2.7/site-packages/guessit-2.1.1-py2.7.egg/guessit/rules/processors.py", line 222, in then
    if match.raw[0] in seps_no_groups and (len(match.raw) < 3 or match.raw[2] not in seps_no_groups):
IndexError: string index out of range
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================

Is there anything can be done?

Thank you

**Comment by ratoaq2** [comment]
Upgrade to latest release: 2.1.4

**Comment by dima-vy** [comment]
Fixed
Thank you :)
