### ISSUE TITLE
guessit compile to standalone executable 

### ISSUE THREAD

**Issue by wittycodes** [guessit-io/guessit#467]
hey toital, you guys have done gr8 work please provide us the solution to this problem 
about compiling guessit to python exe via pyinstaller or py2exe, the old thread was closed  but it's too crucial as we are implementing guessit in one of our applications

```


Traceback (most recent call last):
  File "guessit_api.py", line 1, in <module>
    from guessit import guessit
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\garg decipher\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\guessit\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\garg decipher\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\guessit\api.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\garg decipher\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\guessit\rules\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\garg decipher\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\guessit\rules\properties\episodes.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\garg decipher\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\guessit\rules\properties\title.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\garg decipher\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\guessit\rules\properties\language.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\garg decipher\appdata\local\programs\python\python35-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)


 
```

**Comment by Toilal** [comment]
This stack doesn't mean anything, is it complete ? 

I'll let this issue open for some time, maybe someone will answer. IMHO, py2exe is a mess, it's not been updated since 2014 and you should really avoid to use it at all.

**Comment by wittycode** [comment]
Yeah py2exe certainly is, but i think there are some compatibility issues popping up with pyinstaller

**Comment by wittycode** [comment]
hurray, I have sorted this issue out after some serious includes ....

download from source, the guess-it repository and extract it in dist folder   
`pip install babelfish`  and then modify __init__.py as

![capturebabelfsh](https://user-images.githubusercontent.com/13654949/27807090-4751f4ae-605c-11e7-98b3-e3c055eed40a.PNG)


move `tlds-alpha-by-domain.txt` in `dist/tlds/     `
//it's crucial step to get it work as data array in a.analysis({}) only includes directories and not files 
![website py](https://user-images.githubusercontent.com/13654949/27807098-4f141906-605c-11e7-9154-d80d40f6613c.PNG)


copy `C:\Python34\Lib\site-packages\babelfish\data` directory to ` dist/babelfish/data`
now, run terminal in dist and execute
```
pip install pyinstaller
pyinstaller __main__.py 

```

then, one will notice that __main__.spec file is created
navigate and modify it to include babelfish ,config and  tlds directories


![capture](https://user-images.githubusercontent.com/13654949/27807105-542662b4-605c-11e7-83a7-7adff87f0728.PNG)

> note : if one tries to json.dump() with argument as the guessed dictionary , escape the list objects from dictionary object to get it dumped as json  
> eg.     `json.dumps(guess_filename('SOME VARIABLE'),default=lambda x: None)` 
> 


again run `pyinstaller __main__.py` in terminal
a dist folder is created containg   __main__.exe in __main__ subfolder
This is home for your standalone executable for guessit cli
use `--onefile ` to pack whole application in one .exe file

**Comment by Toilal** [comment]
Thanks for writing this. I think we could apply required changes here.

**Comment by Toilal** [comment]
This gonna happen really soon :p

**Comment by 0-MegaMind-0** [comment]
hmm was this fixed ? Looks like pyinstaller still fails with `ModuleNotFoundError: No module named 'babelfish.converters.alpha2'`
