### ISSUE TITLE
Internal error when guessing a file

### ISSUE THREAD

**Issue by loki495** [guessit-io/guessit#499]
Not sure what else do you need, but I'm getting this error (in Medusa's log, a Sickrage fork) and jsut says "internal error on guessit". Here are the logs:

```
2017-09-27 23:21:36 ERROR    FINDPROPERS :: [3f23fd2] Exception generated: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.3.dev0
string=Doctor.Estraño.HDR.VISIONPLUS.1000.[4K.UHD.2160p.HEVC.X265][BT2020][DTS-5.1.Castellano.DTS-HD.7.1-Ingles+Subs][ES-EN].x264-NEWPCT
options={'allowed_languages': set(['ru', 'hu', 'en', 'nl', 'pt', 'ca', 'de', 'jp', 'sv', 'it', 'fr', 'und', 'es', 'uk', 'mul', 'ro', 'pl', 'he']), 'expected_group': ['TV2LAX9', 'DHD'], 'expected_title': ['12 Monkeys', '13 Reasons Why', 'Sense8', '11.22.63'], 'allowed_countries': set(['gb', 'us']), 'episode_prefer_number': False, 'show_type': None, 'type': 'episode', 'implicit': True}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/medusa/lib/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/opt/medusa/lib/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/opt/medusa/lib/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/opt/medusa/lib/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/opt/medusa/lib/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/opt/medusa/lib/rebulk/rules.py", line 122, in then
    cons.then(matches, next(iterator), context)
  File "/opt/medusa/lib/rebulk/rules.py", line 140, in then
    matches.remove(match)
  File "/usr/lib/python2.7/_abcoll.py", line 689, in remove
    del self[self.index(value)]
  File "/opt/medusa/lib/rebulk/match.py", line 559, in __delitem__
    self._remove_match(match)
  File "/opt/medusa/lib/rebulk/match.py", line 133, in _remove_match
    _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
Traceback (most recent call last):
  File "/opt/medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/opt/medusa/medusa/search/proper.py", line 62, in run
    propers = self._get_proper_results()
  File "/opt/medusa/medusa/search/proper.py", line 153, in _get_proper_results
    cur_proper.parse_result = NameParser().parse(cur_proper.name)
  File "/opt/medusa/medusa/name_parser/parser.py", line 282, in parse
    result = self._parse_string(name)
  File "/opt/medusa/medusa/name_parser/parser.py", line 61, in _parse_string
    guess = guessit.guessit(name, dict(show_type=self.show_type))
  File "/opt/medusa/medusa/name_parser/guessit_parser.py", line 73, in guessit
    result = default_api.guessit(name, options=final_options)
  File "/opt/medusa/lib/guessit/api.py", line 131, in guessit
    raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.3.dev0
string=Doctor.Estraño.HDR.VISIONPLUS.1000.[4K.UHD.2160p.HEVC.X265][BT2020][DTS-5.1.Castellano.DTS-HD.7.1-Ingles+Subs][ES-EN].x264-NEWPCT
options={'allowed_languages': set(['ru', 'hu', 'en', 'nl', 'pt', 'ca', 'de', 'jp', 'sv', 'it', 'fr', 'und', 'es', 'uk', 'mul', 'ro', 'pl', 'he']), 'expected_group': ['TV2LAX9', 'DHD'], 'expected_title': ['12 Monkeys', '13 Reasons Why', 'Sense8', '11.22.63'], 'allowed_countries': set(['gb', 'us']), 'episode_prefer_number': False, 'show_type': None, 'type': 'episode', 'implicit': True}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/medusa/lib/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/opt/medusa/lib/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/opt/medusa/lib/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/opt/medusa/lib/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/opt/medusa/lib/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/opt/medusa/lib/rebulk/rules.py", line 122, in then
    cons.then(matches, next(iterator), context)
  File "/opt/medusa/lib/rebulk/rules.py", line 140, in then
    matches.remove(match)
  File "/usr/lib/python2.7/_abcoll.py", line 689, in remove
    del self[self.index(value)]
  File "/opt/medusa/lib/rebulk/match.py", line 559, in __delitem__
    self._remove_match(match)
  File "/opt/medusa/lib/rebulk/match.py", line 133, in _remove_match
    _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
```

**Comment by ratoaq2** [comment]
This was fixed in the other repo, since it's not a guessit bug.
