### ISSUE TITLE
GuessIt runs into UnicodeEncodeError when filename contains unicode

### ISSUE THREAD

**Issue by breunigs** [guessit-io/guessit#520]
See example below. It's not limited to unicode in the filename, I get the same result when there's unicode characters in the parent folder (and I pass it to guessit, of course). I am not sure if this is a bug in guessit or the docker container. Let me know if I can check anything else to help debugging the issue.

```bash
$ /usr/bin/docker run -it guessit/guessit "whatever 1x01 xxx.mkv"  
For: whatever 1x01 xxx.mkv
GuessIt found: {
    "title": "whatever",
    "season": 1,
    "episode": 1,
    "other": "XXX",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}

$ /usr/bin/docker run -it guessit/guessit "whatever 1x01 💩.mkv"   
For: Traceback (most recent call last):
  File "/root/.pyenv/versions/3.4.3/bin/guessit", line 9, in <module>
    load_entry_point('guessit==2.1.4', 'console_scripts', 'guessit')()
  File "/root/guessit/guessit/__main__.py", line 157, in main
    guess_filename(filename, options)
  File "/root/guessit/guessit/__main__.py", line 34, in guess_filename
    print('For:', filename)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-17: ordinal not in range(128)


$ /usr/bin/docker run -it guessit/guessit --version                
+-------------------------------------------------------+
+                   GuessIt 2.1.4                       +
+-------------------------------------------------------+
+                   Rebulk 0.9.0                        +
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|     https://github.com/guessit-io/guessit/issues.     |
+-------------------------------------------------------+
```

**Comment by ratoaq2** [comment]
It seems to be a problem with the container (probably locale configuration). I was able to execute guessit without any problem in a standard ubuntu installation:

```
~/temp/guessit> guessit --version
+-------------------------------------------------------+
+                   GuessIt 2.1.4                       +
+-------------------------------------------------------+
+                   Rebulk 0.9.0                        +
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|     https://github.com/guessit-io/guessit/issues.     |
+-------------------------------------------------------+
~/temp/guessit> python --version
Python 2.7.14
~/temp/guessit> guessit "whatever 1x01 💩.mkv"
For: whatever 1x01 💩.mkv
GuessIt found: {
    "title": "whatever", 
    "season": 1, 
    "episode": 1, 
    "episode_title": "💩", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
~/temp/guessit> locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_CH.UTF-8
LC_TIME=de_CH.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_CH.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_CH.UTF-8
LC_NAME=de_CH.UTF-8
LC_ADDRESS=de_CH.UTF-8
LC_TELEPHONE=de_CH.UTF-8
LC_MEASUREMENT=de_CH.UTF-8
LC_IDENTIFICATION=de_CH.UTF-8
LC_ALL=
```

**Comment by ratoaq2** [comment]
The locales in the docker image is not set.
A workaround is to run with the following env param:

`sudo /usr/bin/docker run -e LANG=C.UTF-8 -it guessit/guessit "whatever 1x01 💩.mkv"`

```
For: whatever 1x01 💩.mkv
GuessIt found: {
    "title": "whatever",
    "season": 1,
    "episode": 1,
    "episode_title": "💩",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```
