### ISSUE TITLE
Internal error, UnicodeDecodeError

### ISSUE THREAD

**Issue by adamgoldberg** [guessit-io/guessit#544]
Logs & Errors

2018-04-26 20:41:54 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TokyoToshokan] :: [77b2091] DailySearchQueueItem Exception, error: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.4
string=[紅茶屋.(大塚子虎)].GERBERA.(ダーリン・イン・ザ・フランキス).[DL版].zip
options={'allowed_languages': set([u'ru', u'fr', u'en', u'nl', u'sv', u'pt', u'ca', u'de', u'jp', u'it', u'hu', u'und', u'pl', u'uk', u'mul', u'ro', u'es', u'he']), 'expected_group': ['TV2LAX9', 'DHD', '20-40'], 'expected_title': ['Babylon 5', 'Sense8'], 'allowed_countries': set([u'gb', u'us']), 'episode_prefer_number': False, 'show_type': None, 'type': 'episode', 'implicit': True}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/share/Medusa/Medusa/ext/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/usr/local/share/Medusa/Medusa/ext/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/usr/local/share/Medusa/Medusa/ext/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/usr/local/share/Medusa/Medusa/ext/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/usr/local/share/Medusa/Medusa/ext/rebulk/rules.py", line 339, in execute_rule
    when_response = rule.when(matches, context)
  File "/usr/local/share/Medusa/Medusa/medusa/name_parser/rules/rules.py", line 1324, in when
    value = regex.sub(' ', value).strip()
  File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 0: unexpected end of data
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
Traceback (most recent call last):
  File "/usr/local/share/Medusa/Medusa/medusa/search/queue.py", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/usr/local/share/Medusa/Medusa/medusa/search/core.py", line 463, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "/usr/local/share/Medusa/Medusa/medusa/tv/cache.py", line 229, in update_cache
    result = self._parse_item(item)
  File "/usr/local/share/Medusa/Medusa/medusa/tv/cache.py", line 308, in _parse_item
    leechers, size, pubdate)
  File "/usr/local/share/Medusa/Medusa/medusa/tv/cache.py", line 377, in add_cache_entry
    parse_result = parsed_result or NameParser().parse(name)
  File "/usr/local/share/Medusa/Medusa/medusa/name_parser/parser.py", line 366, in parse
    result = self._parse_string(name)
  File "/usr/local/share/Medusa/Medusa/medusa/name_parser/parser.py", line 274, in _parse_string
    guess = guessit.guessit(name, dict(show_type=self.show_type))
  File "/usr/local/share/Medusa/Medusa/medusa/name_parser/guessit_parser.py", line 77, in guessit
    result = default_api.guessit(name, options=final_options)
  File "/usr/local/share/Medusa/Medusa/ext/guessit/api.py", line 132, in guessit
    raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.4
string=[紅茶屋.(大塚子虎)].GERBERA.(ダーリン・イン・ザ・フランキス).[DL版].zip
options={'allowed_languages': set([u'ru', u'fr', u'en', u'nl', u'sv', u'pt', u'ca', u'de', u'jp', u'it', u'hu', u'und', u'pl', u'uk', u'mul', u'ro', u'es', u'he']), 'expected_group': ['TV2LAX9', 'DHD', '20-40'], 'expected_title': ['Babylon 5', 'Sense8'], 'allowed_countries': set([u'gb', u'us']), 'episode_prefer_number': False, 'show_type': None, 'type': 'episode', 'implicit': True}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/share/Medusa/Medusa/ext/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/usr/local/share/Medusa/Medusa/ext/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/usr/local/share/Medusa/Medusa/ext/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/usr/local/share/Medusa/Medusa/ext/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/usr/local/share/Medusa/Medusa/ext/rebulk/rules.py", line 339, in execute_rule
    when_response = rule.when(matches, context)
  File "/usr/local/share/Medusa/Medusa/medusa/name_parser/rules/rules.py", line 1324, in when
    value = regex.sub(' ', value).strip()
  File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 0: unexpected end of data
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
===================================================================

**Comment by Toilal** [comment]
Seems to be fixed inside guessit 3
