### ISSUE TITLE
Error with Subliminal

### ISSUE THREAD

**Issue by henkin67** [guessit-io/guessit#545]
Hello,

I'm using Subliminal to automatic download subtitles for my movies and I got the following error for one particular movie:
```
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/local/bin/subliminal", line 9, in <module>                                                                                                                                                            
    load_entry_point('subliminal==2.0.5', 'console_scripts', 'subliminal')()                                                                                                                                       
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__                                                                                                           
    return self.main(*args, **kwargs)                                                                                                                                                                              
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main                                                                                                               
    rv = self.invoke(ctx)                                                                                                                                                                                          
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke                                                                                                            
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                        
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke                                                                                                             
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                                 
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke                                                                                                             
    return callback(*args, **kwargs)                                                                                                                                                                               
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/decorators.py", line 27, in new_func                                                                                                      
    return f(get_current_context().obj, *args, **kwargs)                                                                                                                                                           
  File "build/bdist.linux-armv7l/egg/subliminal/cli.py", line 403, in download                                                                                                                                     
  File "build/bdist.linux-armv7l/egg/subliminal/core.py", line 211, in download_best_subtitles                                                                                                                     
  File "build/bdist.linux-armv7l/egg/subliminal/score.py", line 106, in compute_score                                                                                                                              
  File "build/bdist.linux-armv7l/egg/subliminal/providers/opensubtitles.py", line 98, in get_matches                                                                                                               
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 54, in guessit                                                                                                                                
    return default_api.guessit(string, options)                                                                                                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 131, in guessit                                                                                                                               
    raise GuessitException(string, options)                                                                                                                                                                        
guessit.api.GuessitException: An internal error has occured in guessit.                                                                                                                                            
===================== Guessit Exception Report =====================                                                                                                                                               
version=2.1.1                                                                                                                                                                                                      
string=Lethal Weapon 2 ()                                                                                                                                                                                          
options={'type': 'movie'}                                                                                                                                                                                          
--------------------------------------------------------------------                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 120, in guessit                                                                                                                               
    matches = self.rebulk.matches(string, options)                                                                                                                                                                 
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rebulk.py", line 288, in matches                                                                                                                             
    self._execute_rules(matches, context)                                                                                                                                                                          
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rebulk.py", line 319, in _execute_rules                                                                                                                      
    rules.execute_all_rules(matches, context)                                                                                                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rules.py", line 318, in execute_all_rules                                                                                                                    
    when_response = execute_rule(rule, matches, context)                                                                                                                                                           
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rules.py", line 343, in execute_rule                                                                                                                         
    rule.then(matches, when_response, context)                                                                                                                                                                     
  File "/usr/local/lib/python2.7/dist-packages/guessit/rules/processors.py", line 222, in then                                                                                                                     
    if match.raw[0] in seps_no_groups and (len(match.raw) < 3 or match.raw[2] not in seps_no_groups):                                                                                                              
IndexError: string index out of range                                                                                                                                                                              
--------------------------------------------------------------------                                                                                                                                               
Please report at https://github.com/guessit-io/guessit/issues.                                                                                                                                                     
====================================================================
```
Do you have any idea from where could come this issue?
Subliminal (and then guessit) is working well with other movies, but not for this particular one. Any idea why ?

**Comment by henkin67** [comment]
In addition below the result of the guessit command on the movie file:
```
$ guessit Lethal\ Weapon\ 2\ \(1989\)\ -\ Bluray-720p\ x264\ DTS.mkv
For: Lethal Weapon 2 (1989) - Bluray-720p x264 DTS.mkv
GuessIt found: {
    "title": "Lethal Weapon 2",
    "year": 1989,
    "format": "BluRay",
    "screen_size": "720p",
    "video_codec": "h264",
    "audio_codec": "DTS",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "movie"
}
```

**Comment by ratoaq2** [comment]
`version=2.1.1`

Please update to the latest version and report back if the issue persists

**Comment by henkin67** [comment]
Thanks ratoaq2, I no more got a guessit exception. It's still not working but I think it's more related to subliminal.
