### ISSUE TITLE
Issue arises after trying to download subtitles

### ISSUE THREAD

**Issue by bkemmer** [guessit-io/guessit#557]
Trying to run subliminal, I faced this output:
```
Downloading subtitles  [#################################---]   94%  0d 00:03:13  Mr.Robot.S03E05.eps3.4_runtime-error.r00.WEBDL-1080p.mkv                                  
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/opensubtitles.py", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 69, in guessit
    return default_api.guessit(string, options)
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 182, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.0.0
string=Mr.Robot.S03E05.WEB-DL.WEB-Rip
options={'type': 'episode'}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 170, in guessit
    matches = self.rebulk.matches(string, options)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/usr/local/lib/python2.7/dist-packages/guessit/rules/processors.py", line 220, in then
    if match.raw[0] in seps_no_groups and (len(match.raw) < 3 or match.raw[2] not in seps_no_groups):
IndexError: string index out of range
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
```

**Comment by bkemmer** [comment]
However, when running just guessit it got the right output, by CLI, maybe this is a problem of subliminal...
```
python __main__.py "Mr.Robot.S03E05.eps3.4_runtime-error.r00.WEBDL-1080p.mkv"
For: Mr.Robot.S03E05.eps3.4_runtime-error.r00.WEBDL-1080p.mkv
GuessIt found: {
    "title": "Mr Robot", 
    "season": 3, 
    "episode": 5, 
    "episode_title": "eps3 4 runtime-error r00", 
    "source": "Web", 
    "screen_size": "1080p", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
python __main__.py --version
+-------------------------------------------------------+
+                   GuessIt 3.0.0                       +
+-------------------------------------------------------+
+                   Rebulk 0.9.0                        +
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|     https://github.com/guessit-io/guessit/issues.     |
+-------------------------------------------------------+
```

**Comment by Toilal** [comment]
It's been fixed in https://github.com/guessit-io/guessit/commit/c6701f987ed4cbad83c2cd67c9107b52337d6b97. You now have to wait for next release.
