### ISSUE TITLE
Internal Error with Japanese

### ISSUE THREAD

**Issue by annomatik** [guessit-io/guessit#559]
Hi!

In Medusa, I have downloaded a Japanese Anime successfully. But in the logs, I have found the error below.

2018-08-02 10:24:17 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TokyoToshokan] :: [f5973b2] DailySearchQueueItem Exception, error: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.4
string=(COMIC1☆9).[0000.(九郎、玖呂葉レイジ)].神田ではトキドキ少女はロリ化する.1学期.(ラブライブ!).zip
options={'allowed_languages': ['de', 'en', 'es', 'ca', 'fr', 'he', 'hu', 'it', 'jp', 'nl', 'pl', 'pt', 'ro', 'ru', 'sv', 'uk', 'mul', 'und'], 'expected_group': ['TV2LAX9', 'DHD', '20-40'], 'expected_title': ['Too Fat for 15: Fighting Back'], 'allowed_countries': ['us', 'gb'], 'episode_prefer_number': False, 'show_type': None, 'type': 'episode', 'implicit': True}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/medusa/ext/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/opt/medusa/ext/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/opt/medusa/ext/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 122, in then
    cons.then(matches, next(iterator), context)
  File "/opt/medusa/ext/rebulk/rules.py", line 161, in then
    if match not in matches:
  File "/usr/lib/python2.7/_abcoll.py", line 613, in __contains__
    if v == value:
  File "/opt/medusa/ext/rebulk/match.py", line 822, in __eq__
    return self.span == other.span and self.value == other.value and self.name == other.name and \
  File "/opt/medusa/ext/rebulk/match.py", line 657, in value
    return self.formatter(self.raw)
ValueError: invalid literal for int() with base 10: '[0000'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
Traceback (most recent call last):
  File "/opt/medusa/medusa/search/queue.py", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/opt/medusa/medusa/search/core.py", line 523, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "/opt/medusa/medusa/tv/cache.py", line 229, in update_cache
    result = self._parse_item(item)
  File "/opt/medusa/medusa/tv/cache.py", line 308, in _parse_item
    leechers, size, pubdate)
  File "/opt/medusa/medusa/tv/cache.py", line 377, in add_cache_entry
    parse_result = parsed_result or NameParser().parse(name)
  File "/opt/medusa/medusa/name_parser/parser.py", line 366, in parse
    result = self._parse_string(name)
  File "/opt/medusa/medusa/name_parser/parser.py", line 274, in _parse_string
    guess = guessit.guessit(name, dict(show_type=self.show_type))
  File "/opt/medusa/medusa/name_parser/guessit_parser.py", line 77, in guessit
    result = default_api.guessit(name, options=final_options)
  File "/opt/medusa/ext/guessit/api.py", line 132, in guessit
    raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.4
string=(COMIC1☆9).[0000.(九郎、玖呂葉レイジ)].神田ではトキドキ少女はロリ化する.1学期.(ラブライブ!).zip
options={'allowed_languages': ['de', 'en', 'es', 'ca', 'fr', 'he', 'hu', 'it', 'jp', 'nl', 'pl', 'pt', 'ro', 'ru', 'sv', 'uk', 'mul', 'und'], 'expected_group': ['TV2LAX9', 'DHD', '20-40'], 'expected_title': ['Too Fat for 15: Fighting Back'], 'allowed_countries': ['us', 'gb'], 'episode_prefer_number': False, 'show_type': None, 'type': 'episode', 'implicit': True}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/medusa/ext/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/opt/medusa/ext/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/opt/medusa/ext/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 122, in then
    cons.then(matches, next(iterator), context)
  File "/opt/medusa/ext/rebulk/rules.py", line 161, in then
    if match not in matches:
  File "/usr/lib/python2.7/_abcoll.py", line 613, in __contains__
    if v == value:
  File "/opt/medusa/ext/rebulk/match.py", line 822, in __eq__
    return self.span == other.span and self.value == other.value and self.name == other.name and \
  File "/opt/medusa/ext/rebulk/match.py", line 657, in value
    return self.formatter(self.raw)
ValueError: invalid literal for int() with base 10: '[0000'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================

**Comment by JohnDoee** [comment]
Try upgrading guessit, I don't see that problem with latest version when running it manually against the given string.


    >>> guessit.guessit(u'(COMIC1☆9).[0000.(九郎、玖呂葉レイジ)].神田ではトキドキ少女はロリ化する.1学期.(ラブライブ!).zip')
    MatchesDict([('release_group', u'COMIC1\u26069'), ('episode', 0), ('title', u'\u795e\u7530\u3067\u306f\u30c8\u30ad\u30c9\u30ad\u5c11\u5973\u306f\u30ed\u30ea\u5316\u3059\u308b 1\u5b66\u671f'), ('episode_title', u'zip'), ('mimetype', u'application/zip'), ('type', u'episode')])

    >>> guessit.__version__
    '3.0.0'

**Comment by annomatik** [comment]
how do I do that? I'm on Raspbian Stretch.

**Comment by JohnDoee** [comment]
After I commented, I checked out Medusa to know exactly that. You have to wait for https://github.com/pymedusa/Medusa/pull/4244

As far as I can see the error doesn't cause problems for you(?), so you literally don't have to do anything.

**Comment by annomatik** [comment]
perfect, thanks :-)

No, no problems, just entries in the log.
