### ISSUE TITLE
Medusa guessit exception 

### ISSUE THREAD

**Issue by eruud** [guessit-io/guessit#596]
```
===================== Guessit Exception Report =====================
version=3.0.4.dev0
string=/media/Downloads/TV/19-2/19-2 (2014) - S03E09 - Gone
options={'allowed_languages': ['de', 'en', 'es', 'ca', 'cs', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'mul', 'und', 'jp'], 'expected_group': ['TV2LAX9', 'DHD', '20-40', 'E7'], 'expected_title': ['OSS 117', 'This is Us', '19-2', 'Doctor.Who.2005'], 'allowed_countries': ['au', 'us', 'gb'], 'advanced_config': {'website': {'prefixes': ['from'], 'safe_tlds': ['com', 'org', 'net'], 'safe_prefixes': ['co', 'com', 'org', 'net'], 'safe_subdomains': ['www']}, 'container': {'info': ['nfo'], 'nzb': ['nzb'], 'subtitles': ['srt', 'idx', 'sub', 'ssa', 'ass'], 'videos': ['3g2', '3gp', '3gp2', 'asf', 'avi', 'divx', 'flv', 'mk3d', 'm4v', 'mk2', 'mka', 'mkv', 'mov', 'mp4', 'mp4a', 'mpeg', 'mpg', 'ogg', 'ogm', 'ogv', 'qt', 'ra', 'ram', 'rm', 'ts', 'wav', 'webm', 'wma', 'wmv', 'iso', 'vob'], 'torrent': ['torrent']}, 'audio_codec': {'audio_channels': {'7.1': ['7ch', '8ch', 're:(7[\\W_][01](?:ch)?)(?=[^\\d]|$)'], '5.1': ['5ch', '6ch', 're:(5[\\W_][01](?:ch)?)(?=[^\\d]|$)', 're:(6[\\W_]0(?:ch)?)(?=[^\\d]|$)'], '2.0': ['2ch', 'stereo', 're:(2[\\W_]0(?:ch)?)(?=[^\\d]|$)'], '1.0': ['1ch', 'mono']}}, 'language': {'language_prefixes': ['true'], 'subtitle_prefixes': ['st', 'v', 'vost', 'subforced', 'fansub', 'hardsub', 'legenda', 'legendas', 'legendado', 'subtitulado', 'soft', 'subtitles'], 'subtitle_affixes': ['sub', 'subs', 'esub', 'esubs', 'subbed', 'custom subbed', 'custom subs', 'custom sub', 'customsubbed', 'customsubs', 'customsub', 'soft subtitles', 'soft subs'], 'language_affixes': ['dublado', 'dubbed', 'dub'], 'synonyms': {'fra': ['fran\xc3\xa7ais', 'vf', 'vff', 'vfi', 'vfq'], 'ell': ['gr', 'greek'], 'jpn': ['jp'], 'por_BR': ['po', 'pb', 'pob', 'ptbr', 'br', 'brazilian'], 'hrv': ['scr'], 'swe': ['se'], 'ukr': ['ua'], 'cat': ['catal\xc3\xa0', 'castellano', 'espanol castellano', 'espa\xc3\xb1ol castellano'], 'ces': ['cz'], 'spa': ['esp', 'espa\xc3\xb1ol', 'espanol'], 'mul': ['multi', 'dl'], 'deu_CH': ['swissgerman', 'swiss german'], 'nld_BE': ['flemish'], 'zho': ['cn']}, 'weak_affixes': ['v', 'audio', 'true'], 'subtitle_suffixes': ['subforced', 'fansub', 'hardsub'], 'language_suffixes': ['audio']}, 'common_words': ['ca', 'cat', 'de', 'he', 'it', 'no', 'por', 'rum', 'se', 'st', 'sub'], 'screen_size': {'frame_rates': ['23.976', '24', '25', '30', '48', '50', '60', '120'], 'max_ar': 1.898, 'min_ar': 1.333, 'progressive': ['360', '480', '540', '576', '900', '1080', '368', '720', '1440', '2160', '4320'], 'interlaced': ['360', '480', '576', '900', '1080']}, 'episodes': {'season_markers': ['s'], 'range_separators': ['-', '~', 'to', 'a'], 'episode_max_range': 100, 'episode_markers': ['xe', 'ex', 'ep', 'e', 'x'], 'season_max_range': 100, 'disc_markers': ['d'], 'season_words': ['season', 'saison', 'seizoen', 'seasons', 'saisons', 'tem', 'temp', 'temporada', 'temporadas', 'stagione'], 'max_range_gap': 1, 'discrete_separators': ['+', '&', 'and', 'et'], 'season_ep_markers': ['x'], 'of_words': ['of', 'sur'], 'all_words': ['All'], 'episode_words': ['episode', 'episodes', 'eps', 'ep', 'episodio', 'episodios', 'capitulo', 'capitulos']}, 'part': {'prefixes': ['pt', 'part']}, 'groups': {'starting': '([{', 'ending': ')]}'}, 'country': {'synonyms': {'BR': ['brazilian', 'bra'], 'CA': ['qu\xc3\xa9bec', 'quebec', 'qc'], 'MX': ['Latinoam\xc3\xa9rica', 'latin america'], 'ES': ['espa\xc3\xb1a'], 'GB': ['UK']}}, 'streaming_service': {'WatchMe': 'WME', 'Univision': 'UNIV', 'ESPN': 'ESPN', 'Doc Club': 'DOCC', 'CNBC': 'CNBC', 'Syfy': 'SYFY', 'iTunes': 'iTunes', 'Netflix': ['NF', 'Netflix'], 'Spike': 'SPIK', 'Playstation Network': 'PSN', 'SBS (AU)': 'SBS', 'SeeSo': ['SESO', 'SeeSo'], 'AOL': 'AOL', 'GloboSat Play': 'GLOB', 'Hulu': 'HULU', 'Crunchy Roll': ['CR', 're:Crunchy-?Roll'], 'CuriosityStream': 'CUR', 'Nickelodeon': ['NICK', 'Nickelodeon'], "America's Test Kitchen": 'ATK', 'Digiturk Diledigin Yerde': 'DDY', 'DC Universe': 'DCU', 'Xbox Video': 'XBOX', 'BravoTV': 'BRAV', 'Canal+': 'CNLP', 'DIY Network': 'DIY', 'National Geographic': ['NATG', 're:National-?Geographic'], 'A&E': ['AE', 'A&E'], 'DPlay': 'DPLY', 'Crackle': 'CRKL', 'Freeform': 'FREE', 'Global': 'GLBL', 'Fox': 'FOX', 'IFC': 'IFC', 'ZDF': 'ZDF', 'Cinemax': 'CMAX', 'Adult Swim': ['AS', 're:Adult-?Swim'], 'Discovery': ['DISC', 'Discovery'], 'TubiTV': 'TUBI', 'AMC': 'AMC', 'Al Jazeera English': 'AJAZ', 'E!': 'ETV', 'Norsk Rikskringkasting': 'NRK', 'Comedians in Cars Getting Coffee': 'CCGC', 'SwearNet': 'SWER', 'PBS': 'PBS', 'ABC Australia': 'AUBC', 'UKTV': 'UKTV', 'NFL': 'NFL', 'NBA TV': ['NBA', 're:NBA-?TV'], 'AnimeLab': 'ANLB', 'Family Jr': 'FJR', 'CBC': 'CBC', 'Hallmark': 'HLMK', 'HBO Go': ['HBO', 're:HBO-?Go'], 'TBS': 'TBS', 'Motor Trend OnDemand': 'MTOD', 'NHL GameCenter': 'GC', 'Lifetime': 'LIFE', 'Daisuki': 'DSKI', 'CTV': 'CTV', 'MSNBC': 'MNBC', 'CHRGD': 'CHGD', 'Disney': ['DSNY', 'Disney'], 'Starz': 'STZ', 'Sveriges Television': 'SVT', 'Deadhouse Films': 'DHF', 'WWE Network': 'WWEN', 'Animal Planet': 'ANPL', 'Yahoo': 'YHOO', 'Country Music Television': 'CMT', 'Pluzz': 'PLUZ', 'Amazon Prime': ['AMZN', 'Amazon', 're:Amazon-?Prime'], 'TV Land': ['TVL', 're:TV-?Land'], 'Cartoon Network': 'CN', 'Stan': 'STAN', 'Comedy Central': ['CC', 're:Comedy-?Central'], 'PBS Kids': 'PBSK', 'Vimeo': 'VMEO', 'El Trece': 'ETTV', 'TLC': 'TLC', 'NBC': 'NBC', 'Sportsnet': 'SNET', 'USA Network': 'USAN', 'Velocity': 'VLCT', 'History': ['HIST', 'History'], 'Family': 'FAM', 'NFL Now': 'NFLN', 'Sprout': 'SPRT', 'UFC': 'UFC', 'FYI Network': 'FYI', 'ITV': 'ITV', 'CSpan': 'CSPN', 'Channel 4': '4OD', 'CWSeed': 'CWS', 'VRV': 'VRV', 'The CW': ['CW', 're:The-?CW'], 'TV3 Ireland': 'TV3', 'RTE One': 'RTE', 'Esquire': 'ESQ', 'Viceland': 'VICE', 'CBS': 'CBS', 'Spike TV': ['SPKE', 're:Spike-?TV'], 'Investigation Discovery': 'ID', 'ePix': 'EPIX', 'ABC': 'AMBC', 'Shomi': 'SHMI', 'HGTV': 'HGTV', 'MTV': 'MTV', 'YouTube Red': 'RED', 'TV4 Sweeden': 'TV4', 'W Network': 'WNET', 'Food Network': 'FOOD', 'Knowledge Network': 'KNOW', 'VH1': 'VH1', 'TFou': 'TFOU', 'ARD': 'ARD', 'BBC iPlayer': ['iP', 're:BBC-?iPlayer']}, 'release_group': {'forbidden_names': ['rip', 'by', 'for', 'par', 'pour', 'bonus'], 'ignored_seps': '[]{}()'}}, 'episode_prefer_number': False, 'show_type': 'normal', 'type': 'episode', 'implicit': True}

Traceback (most recent call last):
  File "/opt/medusa/ext/guessit/api.py", line 210, in guessit
    matches = self.rebulk.matches(string, options)
  File "/opt/medusa/ext/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/opt/medusa/ext/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 316, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 341, in execute_rule
    rule.then(matches, when_response, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 122, in then
    cons.then(matches, next(iterator), context)
  File "/opt/medusa/ext/rebulk/rules.py", line 140, in then
    matches.remove(match)
  File "/usr/lib/python2.7/_abcoll.py", line 689, in remove
    del self[self.index(value)]
  File "/opt/medusa/ext/rebulk/match.py", line 569, in __delitem__
    self._remove_match(match)
  File "/opt/medusa/ext/rebulk/match.py", line 137, in _remove_match
    _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list

Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
```

**Comment by Toilal** [comment]
I'm sorry but I can't reproduce this issue in guessit.

```
? /media/Downloads/TV/19-2/19-2 (2014) - S03E09 - Gone
: date: 2019-02-19
  title: '2'
  year: 2014
  season: 3
  episode: 9
  episode_title: Gone
  type: episode
```

It doesn't give the right serie name though, as `19-2` is guessed as a date, but it can be workaround with `--expected-title` option (or configuration).
