### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by morpheus65535** [guessit-io/guessit#600]
```
'Traceback (most recent call last):
  File "/volume1/@appstore/bazarr/bazarr/get_subtitle.py", line 63, in get_video
    video = parse_video(path, hints=hints, providers=providers, dry_run=dont_use_actual_file)
  File "/volume1/@appstore/bazarr/bazarr/../libs/subzero/video.py", line 58, in parse_video
    skip_hashing=skip_hashing)
  File "/volume1/@appstore/bazarr/bazarr/../libs/subliminal_patch/core.py", line 520, in scan_video
    guessed_result = guessit(guess_from, options=hints)
  File "/volume1/@appstore/bazarr/bazarr/../libs/guessit/api.py", line 54, in guessit
    return default_api.guessit(string, options)
  File "/volume1/@appstore/bazarr/bazarr/../libs/guessit/api.py", line 132, in guessit
    raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.4
string=NiceSerie/Season 02/NiceSerie-S02E04.(2019).Corleone.mkv
options={\'type\': \'episode\', \'expected_title\': [\'NiceSerie\'], \'single_value\': True, \'title\': \'NiceSerie\'}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/volume1/@appstore/bazarr/bazarr/../libs/guessit/api.py", line 120, in guessit
    matches = self.rebulk.matches(string, options)
  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rules.py", line 122, in then
    cons.then(matches, next(iterator), context)
  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rules.py", line 206, in then
    removed = self.remove.then(matches, when_response, context)
  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/rules.py", line 140, in then
    matches.remove(match)
  File "/usr/lib/python2.7/_abcoll.py", line 689, in remove
    del self[self.index(value)]
  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/match.py", line 565, in __delitem__
    self._remove_match(match)
  File "/volume1/@appstore/bazarr/bazarr/../libs/rebulk/match.py", line 133, in _remove_match
    _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
===================================================================='
```

**Comment by morpheus65535** [comment]
This is the last 2.x.x version and, last time we made some test with version 3.x, we had so many issues (tens of movies or series not recognized anymore) that we decided to continue to bundle version 2.1.4 in Bazarr for a while. Is there still support for version 2.1.4?

**Comment by ratoaq2** [comment]
Medusa is using guessit 3.x for a while now supporting so many different patterns for movies and series. There's a migration guide for guessit 2.x to 3.x since some default options changed. Every single issue found by Medusa or by us was added to our regression test suites. If you encounter any issue, I can support you with the right configuration or proper fix.

**Comment by morpheus65535** [comment]
I'm going to look with @pannal to see how we can back port this in our version of subliminal and subliminal_patch: https://github.com/Diaoul/subliminal/commit/78687f45d23b1bc47fae0a5493be0198dc1fd5b5

**Comment by Toilal** [comment]
Please upgrade.
