### ISSUE TITLE
Python 3.8.2 Error

### ISSUE THREAD

**Issue by p1r473** [guessit-io/guessit#639]
Upgraded to latest Python and it seems Guessit broke.

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\guessit\api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "C:\Python3\lib\site-packages\guessit\api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "C:\Python3\lib\site-packages\guessit\rules\__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "C:\Python3\lib\site-packages\guessit\rules\properties\episodes.py", line 162, in episodes
    validator={'__parent__': seps_before}).repeater('+') \
  File "C:\Python3\lib\site-packages\rebulk\chain.py", line 115, in regex
    pattern = self.rebulk.build_re(*pattern, **kwargs)
  File "C:\Python3\lib\site-packages\rebulk\rebulk.py", line 133, in build_re
    return RePattern(*pattern, **kwargs)
  File "C:\Python3\lib\site-packages\rebulk\pattern.py", line 378, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "C:\Python3\lib\site-packages\rebulk\loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "C:\Python3\lib\site-packages\regex\regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "C:\Python3\lib\site-packages\regex\regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'children'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "DownloadSubtitles.py", line 10, in <module>
    videos = [v for v in scan_videos("K:\Shows\watch") if v.age < timedelta(weeks=8)]
  File "C:\Python3\lib\site-packages\subliminal\core.py", line 502, in scan_videos
    video = scan_video(filepath)
  File "C:\Python3\lib\site-packages\subliminal\core.py", line 380, in scan_video
    video = Video.fromguess(path, guessit(path))
  File "C:\Python3\lib\site-packages\guessit\api.py", line 71, in guessit
    return default_api.guessit(string, options)
  File "C:\Python3\lib\site-packages\guessit\api.py", line 222, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.

===================== Guessit Exception Report =====================
version=3.0.4
string=K:\Shows\watch\cachefile.dbm.dat
options={}

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\guessit\api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "C:\Python3\lib\site-packages\guessit\api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "C:\Python3\lib\site-packages\guessit\rules\__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "C:\Python3\lib\site-packages\guessit\rules\properties\episodes.py", line 162, in episodes
    validator={'__parent__': seps_before}).repeater('+') \
  File "C:\Python3\lib\site-packages\rebulk\chain.py", line 115, in regex
    pattern = self.rebulk.build_re(*pattern, **kwargs)
  File "C:\Python3\lib\site-packages\rebulk\rebulk.py", line 133, in build_re
    return RePattern(*pattern, **kwargs)
  File "C:\Python3\lib\site-packages\rebulk\pattern.py", line 378, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "C:\Python3\lib\site-packages\rebulk\loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "C:\Python3\lib\site-packages\regex\regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "C:\Python3\lib\site-packages\regex\regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'children'

**Comment by bxabi** [comment]
I have the same issue.

**Comment by Toilal** [comment]
You have to upgrade rebulk to 2.0.1, which has just been released.

**Comment by p1r473** [comment]
Thanks @Toilal !
