### ISSUE TITLE
BAZARR Error trying to get video information for this file

### ISSUE THREAD

**Issue by lukjod** [guessit-io/guessit#645]
Bazarr Version:
0.8.4.4
Sonarr Version:
2.0.0.5344
Radarr Version:
0.2.0.1480
Operating System:
Linux-4.14.24-qnap-x86_64-with
Python Version:
3.8.2

newest docker development version 0.8.4.4

log
`Message
BAZARR Error trying to get video information for this file: /movies/Arkansas (2020) [Bluray-1080p, AC3, 5.1]/Arkansas.2020.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG[TGx].mkv
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/guessit/api.py", line 120, in guessit
  matches = self.rebulk.matches(string, options)
 File "/app/bazarr/bazarr/../libs/rebulk/rebulk.py", line 288, in matches
  self._execute_rules(matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rebulk.py", line 319, in _execute_rules
  rules.execute_all_rules(matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 318, in execute_all_rules
  when_response = execute_rule(rule, matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 343, in execute_rule
  rule.then(matches, when_response, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 122, in then
  cons.then(matches, next(iterator), context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 206, in then
  removed = self.remove.then(matches, when_response, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 140, in then
  matches.remove(match)
 File "/usr/lib/python3.8/_collections_abc.py", line 997, in remove
  del self[self.index(value)]
 File "/app/bazarr/bazarr/../libs/rebulk/match.py", line 565, in __delitem__
  self._remove_match(match)
 File "/app/bazarr/bazarr/../libs/rebulk/match.py", line 133, in _remove_match
  _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 71, in get_video
  video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
 File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video
  return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 526, in scan_video
  guessed_result = guessit(guess_from, options=hints)
 File "/app/bazarr/bazarr/../libs/guessit/api.py", line 54, in guessit
  return default_api.guessit(string, options)
 File "/app/bazarr/bazarr/../libs/guessit/api.py", line 132, in guessit
  raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=2.1.4
string=Arkansas (2020) [Bluray-1080p, AC3, 5.1]/Arkansas.2020.1080p.BluRay.1400MB.DD5.1.x264-GalaxyRG.mkv
options={\title\: \Arkansas\, \type\: \movie\, \single_value\: True, \expected_title\: [\Arkansas\]}
--------------------------------------------------------------------
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/guessit/api.py", line 120, in guessit
  matches = self.rebulk.matches(string, options)
 File "/app/bazarr/bazarr/../libs/rebulk/rebulk.py", line 288, in matches
  self._execute_rules(matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rebulk.py", line 319, in _execute_rules
  rules.execute_all_rules(matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 318, in execute_all_rules
  when_response = execute_rule(rule, matches, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 343, in execute_rule
  rule.then(matches, when_response, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 122, in then
  cons.then(matches, next(iterator), context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 206, in then
  removed = self.remove.then(matches, when_response, context)
 File "/app/bazarr/bazarr/../libs/rebulk/rules.py", line 140, in then
  matches.remove(match)
 File "/usr/lib/python3.8/_collections_abc.py", line 997, in remove
  del self[self.index(value)]
 File "/app/bazarr/bazarr/../libs/rebulk/match.py", line 565, in __delitem__
  self._remove_match(match)
 File "/app/bazarr/bazarr/../libs/rebulk/match.py", line 133, in _remove_match
  _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list`

I have also sent this error onto bazarr github
[https://github.com/morpheus65535/bazarr/issues/984](url)

**Comment by ratoaq2** [comment]
If I'm not mistaken, bazarr uses an old guessit version. You need to see if that happens with the current guessit version

**Comment by morpheus65535** [comment]
The problem arrise with 2.1.4. I cannot reproduce it with 3.1.1. I'll see to upgrade guessit sometime in the future.
