### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by sammcj** [guessit-io/guessit#657]
```
===================== Guessit Exception Report =====================
version=3.1.1
string=<REDACTED>
options={'expected_title': ['OSS 117', 'This is Us', 'Comedy Central Stand-Up Presents…', '8 Out of 10 Cats', 'Reno 911!', 'Tosh 0', 'Tosh.0', '8 Out of 10 Cats Does Countdown', 'Room 104', 'Travel Man: 48 Hours in...', 'Brooklyn Nine-Nine', '7 Days', 'Wu-Tang Clan: Of Mics and Men', 'Avenue 5', 'Code 404', 'Wu-Tang: An American Saga', 'Ballmastrz: 9009', 'Aqua Unit Patrol Squad 1', "Dara O Briain's Go 8 Bit"], 'allowed_countries': ['au', 'gb', 'us'], 'allowed_languages': ['ca', 'cs', 'de', 'en', 'es', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'mul', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'und', 'jp'], 'advanced_config': {'common_words': ['ca', 'cat', 'de', 'he', 'it', 'no', 'por', 'rum', 'se', 'st', 'sub'], 'groups': {'starting': '([{', 'ending': ')]}'}, 'audio_codec': {'audio_channels': {'1.0': ['1ch', 'mono'], '2.0': ['2ch', 'stereo', 're:(2[\\W_]0(?:ch)?)(?=[^\\d]|$)'], '5.1': ['5ch', '6ch', 're:(5[\\W_][01](?:ch)?)(?=[^\\d]|$)', 're:(6[\\W_]0(?:ch)?)(?=[^\\d]|$)'], '7.1': ['7ch', '8ch', 're:(7[\\W_][01](?:ch)?)(?=[^\\d]|$)']}}, 'container': {'subtitles': ['srt', 'idx', 'sub', 'ssa', 'ass'], 'info': ['nfo'], 'videos': ['3g2', '3gp', '3gp2', 'asf', 'avi', 'divx', 'flv', 'iso', 'm4v', 'mk2', 'mk3d', 'mka', 'mkv', 'mov', 'mp4', 'mp4a', 'mpeg', 'mpg', 'ogg', 'ogm', 'ogv', 'qt', 'ra', 'ram', 'rm', 'ts', 'vob', 'wav', 'webm', 'wma', 'wmv'], 'torrent': ['torrent'], 'nzb': ['nzb']}, 'country': {'synonyms': {'ES': ['españa'], 'GB': ['UK'], 'BR': ['brazilian', 'bra'], 'CA': ['québec', 'quebec', 'qc'], 'MX': ['Latinoamérica', 'latin america']}}, 'episodes': {'season_max_range': 100, 'episode_max_range': 100, 'max_range_gap': 1, 'season_markers': ['s'], 'season_ep_markers': ['x'], 'disc_markers': ['d'], 'episode_markers': ['xe', 'ex', 'ep', 'e', 'x'], 'range_separators': ['-', '~', 'to', 'a'], 'discrete_separators': ['+', '&', 'and', 'et'], 'season_words': ['season', 'saison', 'seizoen', 'seasons', 'saisons', 'tem', 'temp', 'temporada', 'temporadas', 'stagione'], 'episode_words': ['episode', 'episodes', 'eps', 'ep', 'episodio', 'episodios', 'capitulo', 'capitulos'], 'of_words': ['of', 'sur'], 'all_words': ['All']}, 'language': {'synonyms': {'ell': ['gr', 'greek'], 'spa': ['esp', 'español', 'espanol'], 'fra': ['français', 'vf', 'vff', 'vfi', 'vfq'], 'swe': ['se'], 'por_BR': ['po', 'pb', 'pob', 'ptbr', 'br', 'brazilian'], 'deu_CH': ['swissgerman', 'swiss german'], 'nld_BE': ['flemish'], 'cat': ['català', 'castellano', 'espanol castellano', 'español castellano'], 'ces': ['cz'], 'ukr': ['ua'], 'zho': ['cn'], 'jpn': ['jp'], 'hrv': ['scr'], 'mul': ['multi', 'dl']}, 'subtitle_affixes': ['sub', 'subs', 'esub', 'esubs', 'subbed', 'custom subbed', 'custom subs', 'custom sub', 'customsubbed', 'customsubs', 'customsub', 'soft subtitles', 'soft subs'], 'subtitle_prefixes': ['st', 'vost', 'subforced', 'fansub', 'hardsub', 'legenda', 'legendas', 'legendado', 'subtitulado', 'soft', 'subtitles'], 'subtitle_suffixes': ['subforced', 'fansub', 'hardsub'], 'language_affixes': ['dublado', 'dubbed', 'dub'], 'language_prefixes': ['true'], 'language_suffixes': ['audio'], 'weak_affixes': ['v', 'audio', 'true']}, 'part': {'prefixes': ['pt', 'part']}, 'release_group': {'forbidden_names': ['bonus', 'by', 'for', 'par', 'pour', 'rip'], 'ignored_seps': '[]{}()'}, 'screen_size': {'frame_rates': ['23.976', '24', '25', '29.970', '30', '48', '50', '60', '120'], 'min_ar': 1.333, 'max_ar': 1.898, 'interlaced': ['360', '480', '576', '900', '1080'], 'progressive': ['360', '480', '540', '576', '900', '1080', '368', '720', '1440', '2160', '4320']}, 'website': {'safe_tlds': ['com', 'net', 'org'], 'safe_subdomains': ['www'], 'safe_prefixes': ['co', 'com', 'net', 'org'], 'prefixes': ['from']}, 'streaming_service': {'A&E': ['AE', 'A&E'], 'ABC': 'AMBC', 'ABC Australia': 'AUBC', 'Al Jazeera English': 'AJAZ', 'AMC': 'AMC', 'Amazon Prime': ['AMZN', 'Amazon', 're:Amazon-?Prime'], 'Adult Swim': ['AS', 're:Adult-?Swim'], "America's Test Kitchen": 'ATK', 'Animal Planet': 'ANPL', 'AnimeLab': 'ANLB', 'AOL': 'AOL', 'ARD': 'ARD', 'BBC iPlayer': ['iP', 're:BBC-?iPlayer'], 'BravoTV': 'BRAV', 'Canal+': 'CNLP', 'Cartoon Network': 'CN', 'CBC': 'CBC', 'CBS': 'CBS', 'CNBC': 'CNBC', 'Comedy Central': ['CC', 're:Comedy-?Central'], 'Channel 4': '4OD', 'CHRGD': 'CHGD', 'Cinemax': 'CMAX', 'Country Music Television': 'CMT', 'Comedians in Cars Getting Coffee': 'CCGC', 'Crunchy Roll': ['CR', 're:Crunchy-?Roll'], 'Crackle': 'CRKL', 'CSpan': 'CSPN', 'CTV': 'CTV', 'CuriosityStream': 'CUR', 'CWSeed': 'CWS', 'Daisuki': 'DSKI', 'DC Universe': 'DCU', 'Deadhouse Films': 'DHF', 'DramaFever': ['DF', 'DramaFever'], 'Digiturk Diledigin Yerde': 'DDY', 'Discovery': ['DISC', 'Discovery'], 'Disney': ['DSNY', 'Disney'], 'DIY Network': 'DIY', 'Doc Club': 'DOCC', 'DPlay': 'DPLY', 'E!': 'ETV', 'ePix': 'EPIX', 'El Trece': 'ETTV', 'ESPN': 'ESPN', 'Esquire': 'ESQ', 'Family': 'FAM', 'Family Jr': 'FJR', 'Food Network': 'FOOD', 'Fox': 'FOX', 'Freeform': 'FREE', 'FYI Network': 'FYI', 'Global': 'GLBL', 'GloboSat Play': 'GLOB', 'Hallmark': 'HLMK', 'HBO Go': ['HBO', 're:HBO-?Go'], 'HGTV': 'HGTV', 'History': ['HIST', 'History'], 'Hulu': 'HULU', 'Investigation Discovery': 'ID', 'IFC': 'IFC', 'iTunes': 'iTunes', 'ITV': 'ITV', 'Knowledge Network': 'KNOW', 'Lifetime': 'LIFE', 'Motor Trend OnDemand': 'MTOD', 'MBC': ['MBC', 'MBCVOD'], 'MSNBC': 'MNBC', 'MTV': 'MTV', 'National Geographic': ['NATG', 're:National-?Geographic'], 'NBA TV': ['NBA', 're:NBA-?TV'], 'NBC': 'NBC', 'Netflix': ['NF', 'Netflix'], 'NFL': 'NFL', 'NFL Now': 'NFLN', 'NHL GameCenter': 'GC', 'Nickelodeon': ['NICK', 'Nickelodeon'], 'Norsk Rikskringkasting': 'NRK', 'OnDemandKorea': ['ODK', 'OnDemandKorea'], 'PBS': 'PBS', 'PBS Kids': 'PBSK', 'Playstation Network': 'PSN', 'Pluzz': 'PLUZ', 'RTE One': 'RTE', 'SBS (AU)': 'SBS', 'SeeSo': ['SESO', 'SeeSo'], 'Shomi': 'SHMI', 'Spike': 'SPIK', 'Spike TV': ['SPKE', 're:Spike-?TV'], 'Sportsnet': 'SNET', 'Sprout': 'SPRT', 'Stan': 'STAN', 'Starz': 'STZ', 'Sveriges Television': 'SVT', 'SwearNet': 'SWER', 'Syfy': 'SYFY', 'TBS': 'TBS', 'TFou': 'TFOU', 'The CW': ['CW', 're:The-?CW'], 'TLC': 'TLC', 'TubiTV': 'TUBI', 'TV3 Ireland': 'TV3', 'TV4 Sweeden': 'TV4', 'TVING': 'TVING', 'TV Land': ['TVL', 're:TV-?Land'], 'UFC': 'UFC', 'UKTV': 'UKTV', 'Univision': 'UNIV', 'USA Network': 'USAN', 'Velocity': 'VLCT', 'VH1': 'VH1', 'Viceland': 'VICE', 'Viki': 'VIKI', 'Vimeo': 'VMEO', 'VRV': 'VRV', 'W Network': 'WNET', 'WatchMe': 'WME', 'WWE Network': 'WWEN', 'Xbox Video': 'XBOX', 'Yahoo': 'YHOO', 'YouTube Red': 'RED', 'ZDF': 'ZDF'}}, 'show_type': 'normal', 'type': 'episode', 'implicit': True, 'episode_prefer_number': False, 'expected_group': ['TV2LAX9', 'DHD', '20-40', 'E7']}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/medusa/ext/guessit/api.py", line 210, in guessit
    matches = self.rebulk.matches(string, options)
  File "/opt/medusa/ext/rebulk/rebulk.py", line 115, in matches
    self._execute_rules(matches, context)
  File "/opt/medusa/ext/rebulk/rebulk.py", line 146, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 316, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 341, in execute_rule
    rule.then(matches, when_response, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 122, in then
    cons.then(matches, next(iterator), context)
  File "/opt/medusa/ext/rebulk/rules.py", line 140, in then
    matches.remove(match)
  File "/usr/lib64/python3.6/_collections_abc.py", line 1004, in remove
    del self[self.index(value)]
  File "/opt/medusa/ext/rebulk/match.py", line 569, in __delitem__
    self._remove_match(match)
  File "/opt/medusa/ext/rebulk/match.py", line 137, in _remove_match
    _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
Traceback (most recent call last):
  File "/opt/medusa/ext/guessit/api.py", line 210, in guessit
    matches = self.rebulk.matches(string, options)
  File "/opt/medusa/ext/rebulk/rebulk.py", line 115, in matches
    self._execute_rules(matches, context)
  File "/opt/medusa/ext/rebulk/rebulk.py", line 146, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 316, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 341, in execute_rule
    rule.then(matches, when_response, context)
  File "/opt/medusa/ext/rebulk/rules.py", line 122, in then
    cons.then(matches, next(iterator), context)
  File "/opt/medusa/ext/rebulk/rules.py", line 140, in then
    matches.remove(match)
  File "/usr/lib64/python3.6/_collections_abc.py", line 1004, in remove
    del self[self.index(value)]
  File "/opt/medusa/ext/rebulk/match.py", line 569, in __delitem__
    self._remove_match(match)
  File "/opt/medusa/ext/rebulk/match.py", line 137, in _remove_match
    _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/medusa/show_queue.py", line 696, in run
    self.show.refresh_dir()
  File "/opt/medusa/medusa/tv/series.py", line 1842, in refresh_dir
    self.load_episodes_from_dir()
  File "/opt/medusa/medusa/tv/series.py", line 1067, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/opt/medusa/medusa/tv/series.py", line 1370, in make_ep_from_file
    'normal', 'anime')[self.is_anime]).parse(filepath)
  File "/opt/medusa/medusa/name_parser/parser.py", line 389, in parse
    result = self._parse_string(name)
  File "/opt/medusa/medusa/name_parser/parser.py", line 293, in _parse_string
    guess = guessit.guessit(name, dict(show_type=self.show_type))
  File "/opt/medusa/medusa/name_parser/guessit_parser.py", line 80, in guessit
    result = default_api.guessit(name, options=final_options)
  File "/opt/medusa/ext/guessit/api.py", line 222, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
```

**Comment by Toilal** [comment]
Could you provide the real input string, instead of `<REDACTED>` ?

**Comment by morpheus65535** [comment]
If it can help, we had a couple of those issue with Bazarr: https://github.com/morpheus65535/bazarr/issues?q=is%3Aissue+ValueError%3A+list.remove%28x%29%3A+x+not+in+list

**Comment by sammcj** [comment]
Oh sorry I missed your reply Toilal, I cleared the errors recently - I'll have to update this when I get them again.

**Comment by sammcj** [comment]
Hmm it hasn't come back, I'll close this to keep the issues clean and log a new ticket and link it if it reoccurs.

Thank you,
