### ISSUE TITLE
BAZARR Error (An internal error has occured in guessit.===================== Guessit Exception Report

### ISSUE THREAD

**Issue by cphmichael** [guessit-io/guessit#725]
Basarr: v1.0.3-beta.27
Sonarr: 3.0.6.1457
Radarr: 4.0.4.5922
unRAID: 6.9.2

When searching for subtitles for "Reacher S01E07 Reacher Said Nothing" a guessit error occure:

`Traceback (most recent call last):\n  File "/app/bin/bazarr/../libs/guessit/api.py", line 209, in guessit\n    matches = self.rebulk.matches(string, options)\n  File "/app/bin/bazarr/../libs/rebulk/rebulk.py", line 115, in matches\n    self._execute_rules(matches, context)\n  File "/app/bin/bazarr/../libs/rebulk/rebulk.py", line 146, in _execute_rules\n    rules.execute_all_rules(matches, context)\n  File "/app/bin/bazarr/../libs/rebulk/rules.py", line 312, in execute_all_rules\n    when_response = execute_rule(rule, matches, context)\n  File "/app/bin/bazarr/../libs/rebulk/rules.py", line 337, in execute_rule\n    rule.then(matches, when_response, context)\n  File "/app/bin/bazarr/../libs/guessit/rules/properties/episode_title.py", line 119, in then\n    matches.remove(title)\n  File "/usr/lib/python3.9/_collections_abc.py", line 1108, in remove\n    del self[self.index(value)]\n  File "/app/bin/bazarr/../libs/rebulk/match.py", line 554, in __delitem__\n    self._remove_match(match)\n  File "/app/bin/bazarr/../libs/rebulk/match.py", line 129, in _remove_match\n    _BaseMatches._base_remove(self._tag_dict[tag], match)\nValueError: list.remove(x): x not in list\n--------------------------------------------------------------------\nPlease report at https://github.com/guessit-io/guessit/issues.\n====================================================================`

![image](https://user-images.githubusercontent.com/45288008/152781387-757e254f-d330-4f23-bb66-a7c7b28a8626.png)

**Comment by BacchusFLT** [comment]
My Log is filled with the same.  I also have the reference to expected title being "OSS 117" and "This  is Us"

A few examples:

BAZARR Error (An internal error has occured in guessit.===================== Guessit Exception Report =====================version=3.4.3string=Yakuza Princess [2021]\Yakuza Princess (2021).avioptions={'expected_title': ['OSS 117', 'This is Us', 'Yakuza Princess'], 'allowed_countries': ['au', 'gb', 'us'], 'allowed_languages': ['ca', 'cs', 'de', 'en', 'es', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'mul', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'und'], 'advanced_config': {'common_words': ['ca', 'cat', 'de', 'he', 'it', 'no', 'por', 'rum', 'se', 'st', 'sub'], 'groups': {'starting': '([{', 'ending': ')]}'}, 'audio_codec': {'audio_codec': {'MP3': {'string': ['MP3', 'LAME'], 'regex': ['LAME(?:\\d)+-?(?:\\d)+']}, 'MP2': 'MP2', 'Dolby Digital': {'string': ['Dolby', 'DolbyDigital'], 'regex': ['Dolby-Digital', 'DD', 'AC3D?']}, 'Dolby Atmos': {'string': ['Atmos'], 'regex': ['Dolby-?Atmos']}, 'AAC': 'AAC', 'Dolby Digital Plus': ['EAC3', 'DDP', 'DD+'], 'FLAC': 'Flac', 'DTS': 'DTS', 'DTS-HD': {'regex': ['DTS-?HD', 'DTS(?=-?MA)'], 'conflict_solver': "lambda match, other: other if other.name == 'audio_codec' else '__default__'"}, 'Dolby TrueHD': {'regex': ['True-?HD']}, 'Opus': 'Opus', 'Vorbis': 'Vorbis', 'PCM': 'PCM', 'LPCM': 'LPCM'}, 'audio_channels': {'1.0': ['1ch', 'mono', 're:(1[\\W_]0(?:ch)?)(?=[^\\d]

BAZARR Error (An internal error has occured in guessit.===================== Guessit Exception Report =====================version=3.4.3string=Tommy [1975]\Tommy (1975).avioptions={'expected_title': ['OSS 117', 'This is Us', 'Tommy'], 'allowed_countries': ['au', 'gb', 'us'], 'allowed_languages': ['ca', 'cs', 'de', 'en', 'es', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'mul', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'und'], 'advanced_config': {'common_words': ['ca', 'cat', 'de', 'he', 'it', 'no', 'por', 'rum', 'se', 'st', 'sub'], 'groups': {'starting': '([{', 'ending': ')]}'}, 'audio_codec': {'audio_codec': {'MP3': {'string': ['MP3', 'LAME'], 'regex': ['LAME(?:\\d)+-?(?:\\d)+']}, 'MP2': 'MP2', 'Dolby Digital': {'string': ['Dolby', 'DolbyDigital'], 'regex': ['Dolby-Digital', 'DD', 'AC3D?']}, 'Dolby Atmos': {'string': ['Atmos'], 'regex': ['Dolby-?Atmos']}, 'AAC': 'AAC', 'Dolby Digital Plus': ['EAC3', 'DDP', 'DD+'], 'FLAC': 'Flac', 'DTS': 'DTS', 'DTS-HD': {'regex': ['DTS-?HD', 'DTS(?=-?MA)'], 'conflict_solver': "lambda match, other: other if other.name == 'audio_codec' else '__default__'"}, 'Dolby TrueHD': {'regex': ['True-?HD']}, 'Opus': 'Opus', 'Vorbis': 'Vorbis', 'PCM': 'PCM', 'LPCM': 'LPCM'}, 'audio_channels': {'1.0': ['1ch', 'mono', 're:(1[\\W_]0(?:ch)?)(?=[^\\d]

**Comment by BacchusFLT** [comment]
Both the two above are movies. The same is applicable for TV, just to clarify that:

BAZARR Error (An internal error has occured in guessit.===================== Guessit Exception Report =====================version=3.4.3string=_TV\CSI Crime Scene Investigation (2000)\CSI- Crime Scene Investigation - S15E18 - The End Game.mkvoptions={'expected_title': ['OSS 117', 'This is Us', 'CSI: Crime Scene Investigation'], 'allowed_countries': ['au', 'gb', 'us'], 'allowed_languages': ['ca', 'cs', 'de', 'en', 'es', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'mul', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'und'], 'advanced_config': {'common_words': ['ca', 'cat', 'de', 'he', 'it', 'no', 'por', 'rum', 'se', 'st', 'sub'], 'groups': {'starting': '([{', 'ending': ')]}'}, 'audio_codec': {'audio_codec': {'MP3': {'string': ['MP3', 'LAME'], 'regex': ['LAME(?:\\d)+-?(?:\\d)+']}, 'MP2': 'MP2', 'Dolby Digital': {'string': ['Dolby', 'DolbyDigital'], 'regex': ['Dolby-Digital', 'DD', 'AC3D?']}, 'Dolby Atmos': {'string': ['Atmos'], 'regex': ['Dolby-?Atmos']}, 'AAC': 'AAC', 'Dolby Digital Plus': ['EAC3', 'DDP', 'DD+'], 'FLAC': 'Flac', 'DTS': 'DTS', 'DTS-HD': {'regex': ['DTS-?HD', 'DTS(?=-?MA)'], 'conflict_solver': "lambda match, other: other if other.name == 'audio_codec' else '__default__'"}, 'Dolby TrueHD': {'regex': ['True-?HD']}, 'Opus': 'Opus', 'Vorbis': 'Vorbis', 'PCM': 'PCM', 'LPCM': 'LPCM'}, 'audio_channels': {'1.0': ['1ch', 'mono', 're:(1[\\W_]0(?:ch)?)(?=[^\\d]

**Comment by akcryptoguy** [comment]
Similar errors.  Bazarr still seems to be downloading some subs here and there but I have an awful lot of these types of error messages in my logs.

BAZARR Error (An internal error has occured in guessit.===================== Guessit Exception Report =====================version=3.4.3string=The Butterfly Effect (2004)/The Butterfly Effect (2004).mkvoptions={'expected_title': ['OSS 117', 'This is Us', 'The Butterfly Effect'], 'allowed_countries': ['au', 'gb', 'us'], 'allowed_languages': ['ca', 'cs', 'de', 'en', 'es', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'mul', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'und'], 'advanced_config': {'common_words': ['ca', 'cat', 'de', 'he', 'it', 'no', 'por', 'rum', 'se', 'st', 'sub'], 'groups': {'starting': '([{', 'ending': ')]}'}, 'audio_codec': {'audio_codec': {'MP3': {'string': ['MP3', 'LAME'], 'regex': ['LAME(?:\\d)+-?(?:\\d)+']}, 'MP2': 'MP2', 'Dolby Digital': {'string': ['Dolby', 'DolbyDigital'], 'regex': ['Dolby-Digital', 'DD', 'AC3D?']}, 'Dolby Atmos': {'string': ['Atmos'], 'regex': ['Dolby-?Atmos']}, 'AAC': 'AAC', 'Dolby Digital Plus': ['EAC3', 'DDP', 'DD+'], 'FLAC': 'Flac', 'DTS': 'DTS', 'DTS-HD': {'regex': ['DTS-?HD', 'DTS(?=-?MA)'], 'conflict_solver': "lambda match, other: other if other.name == 'audio_codec' else '__default__'"}, 'Dolby TrueHD': {'regex': ['True-?HD']}, 'Opus': 'Opus', 'Vorbis': 'Vorbis', 'PCM': 'PCM', 'LPCM': 'LPCM'}, 'audio_channels': {'1.0': ['1ch', 'mono', 're:(1[\\W_]0(?:ch)?)(?=[^\\d]

**Comment by Toilal** [comment]
This no longer reproduces on `develop`: `guessit("Reacher S01E07 Reacher Said Nothing")` parses without any exception (`title: Reacher`). The crash was on an older release.

Closing as resolved — please reopen with the exact string if you still hit it on the latest version.
