### ISSUE TITLE
Error on click manual download

### ISSUE THREAD

**Issue by alz3abi** [guessit-io/guessit#783]
Error when click to manual search.

`Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 200, in guessit
    config = self.configure(options, sanitize_options=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 162, in configure
    config = load_config(options)
             ^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/guessit/options.py", line 160, in load_config
    default_options_data = read_text(\'guessit.config\', \'options.json\')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/guessit/options.py", line 22, in read_text
    return files(package).joinpath(filename).read_text()  # pylint:disable=unspecified-encoding
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "/usr/lib/python3.11/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc3 in position 5608: ordinal not in range(128)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 41, in get_video
    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video
    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 838, in scan_video
    guessed_result = guessit(path, options=hints)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 74, in guessit
    return default_api.guessit(string, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 225, in guessit
    raise GuessitException(string, options) from err
guessit.api.GuessitException: An internal error has occurred in guessit.
===================== Guessit Exception Report =====================
version=3.8.0
string=/tv/House of the Dragon/House.of.the.Dragon.S01E04.1080p.BluRay.x265-RARBG.mp4
options={\'title\': \'House of the Dragon\', \'type\': \'episode\', \'single_value\': True}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 200, in guessit
    config = self.configure(options, sanitize_options=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 162, in configure
    config = load_config(options)
             ^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/guessit/options.py", line 160, in load_config
    default_options_data = read_text(\'guessit.config\', \'options.json\')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/guessit/options.py", line 22, in read_text
    return files(package).joinpath(filename).read_text()  # pylint:disable=unspecified-encoding
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "/usr/lib/python3.11/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc3 in position 5608: ordinal not in range(128)
--------------------------------------------------------------------
`

**Comment by theadzik** [comment]
```txt
BAZARR Error (An internal error has occurred in guessit.
===================== Guessit Exception Report =====================
version=3.8.0
string=/downloads/movies/The Drama (2026)/the.drama.2026.1080p.webrip.x264.aac5.1-yts.bz.mp4
options={'title': 'The Drama', 'type': 'movie', 'single_value': True}
--------------------------------------------------------------------
Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 200, in guessit

    config = self.configure(options, sanitize_options=False)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 162, in configure

    config = load_config(options)

             ^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/guessit/options.py", line 160, in load_config

    default_options_data = read_text(\'guessit.config\', \'options.json\')

                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/guessit/options.py", line 22, in read_text

    return files(package).joinpath(filename).read_text()  # pylint:disable=unspecified-encoding

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/pathlib.py", line 1028, in read_text

    return f.read()

           ^^^^^^^^

  File "/usr/lib/python3.12/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

UnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc3 in position 5608: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../bazarr/subtitles/utils.py", line 35, in get_video

    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=False, providers=providers)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../custom_libs/subzero/video.py", line 61, in parse_video

    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 852, in scan_video

    guessed_result = guessit(path, options=hints)

                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 74, in guessit

    return default_api.guessit(string, options)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 225, in guessit

    raise GuessitException(string, options) from err

guessit.api.GuessitException: An internal error has occurred in guessit.

===================== Guessit Exception Report =====================

version=3.8.0

string=/downloads/movies/The Drama (2026)/the.drama.2026.1080p.webrip.x264.aac5.1-yts.bz.mp4

options={\'title\': \'The Drama\', \'type\': \'movie\', \'single_value\': True}

--------------------------------------------------------------------

Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 200, in guessit

    config = self.configure(options, sanitize_options=False)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/guessit/api.py", line 162, in configure

    config = load_config(options)

             ^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/guessit/options.py", line 160, in load_config

    default_options_data = read_text(\'guessit.config\', \'options.json\')

                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/bazarr/bin/bazarr/../libs/guessit/options.py", line 22, in read_text

    return files(package).joinpath(filename).read_text()  # pylint:disable=unspecified-encoding

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/pathlib.py", line 1028, in read_text

    return f.read()

           ^^^^^^^^

  File "/usr/lib/python3.12/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

UnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc3 in position 5608: ordinal not in range(128)

--------------------------------------------------------------------

Please report at https://github.com/guessit-io/guessit/issues.

====================================================================
```

**Comment by Toilal** [comment]
The traceback fails in `read_text(...)` while loading guessit's bundled `guessit/config/options.json` through `importlib.resources`. That code path is unchanged on current `develop` and works for a standard pip install — the failure is the packaged/frozen Bazarr distribution not shipping (or not exposing) guessit's data file via `importlib.resources`. That's a packaging/environment issue rather than a guessit-logic bug.

Closing — please reopen with a standalone repro (`pip install guessit` then `python -c "import guessit; print(guessit.guessit('Movie.2020.1080p.mkv'))"`) and the guessit version if it still happens outside the bundled Bazarr.
